= What is {page-component-title} for?

image::shared:what-is-blob.svg[]

{page-component-title} is a declarative data streaming service that solves a wide range of data engineering problems with simple, chained, stateless xref:components:processors/about.adoc[processing steps]. It implements transaction based resiliency with back pressure, so when connecting to at-least-once sources and sinks it's able to guarantee at-least-once delivery without needing to persist messages during transit.

It's xref:guides:getting_started.adoc[simple to deploy], comes with a wide range of <<components,connectors>>, and is totally data agnostic, making it easy to drop into your existing infrastructure. {page-component-title} has functionality that overlaps with integration frameworks, log aggregators and ETL workflow engines, and can therefore be used to complement these traditional data engineering tools or act as a simpler alternative.

{page-component-title} is ready to commit to this relationship, are you?

xref:guides:getting_started.adoc[Get started].

== Components

=== Inputs

components_by_category::[input]

---

=== Processors

components_by_category::[processor]

---

=== Outputs

components_by_category::[output]