= memory
// tag::single-source[]
:type: buffer
:status: stable
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Stores consumed messages in memory and acknowledges them at the input level. During shutdown Redpanda Connect will make a best attempt at flushing all remaining messages before exiting cleanly.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
buffer:
  memory:
    limit: 524288000
    batch_policy:
      enabled: false
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
buffer:
  memory:
    limit: 524288000
    batch_policy:
      enabled: false
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
```

--
======

This buffer is appropriate when consuming messages from inputs that do not gracefully handle back pressure and where delivery guarantees aren't critical.

This buffer has a configurable limit, where consumption will be stopped with back pressure upstream if the total size of messages in the buffer reaches this amount. Since this calculation is only an estimate, and the real size of messages in RAM is always higher, it is recommended to set the limit significantly below the amount of RAM available.

== Delivery guarantees

This buffer intentionally weakens the delivery guarantees of the pipeline and therefore should never be used in places where data loss is unacceptable.

== Batching

It is possible to batch up messages sent from this buffer using a xref:configuration:batching.adoc#batch-policy[batch policy].

== Fields

[data_template, redpanda-connect:ROOT:example$connect.json, redpanda-connect:ROOT:example$overrides.json]
--

{{#selectByJsonPath this "$.buffers[?(@.name=='memory')]"}}

{{renderConnectFields this.config.children}}

{{/selectByJsonPath}}

--

// end::single-source[]