= sqlite
// tag::single-source[]
:type: buffer
:status: stable
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Stores messages in an SQLite database and acknowledges them at the input level.

```yml
# Config fields, showing default values
buffer:
  sqlite:
    path: "" # No default (required)
    pre_processors: [] # No default (optional)
    post_processors: [] # No default (optional)
```

Stored messages are then consumed as a stream from the database and deleted only once they are successfully sent at the output level. If the service is restarted Redpanda Connect will make a best attempt to finish delivering messages that are already read from the database, and when it starts again it will consume from the oldest message that has not yet been delivered.

== Delivery guarantees

Messages are not acknowledged at the input level until they have been added to the SQLite database, and they are not removed from the SQLite database until they have been successfully delivered. This means at-least-once delivery guarantees are preserved in cases where the service is shut down unexpectedly. However, since this process relies on interaction with the disk (wherever the SQLite DB is stored) these delivery guarantees are not resilient to disk corruption or loss.

== Batching

Messages that are logically batched at the point where they are added to the buffer will continue to be associated with that batch when they are consumed. This buffer is also more efficient when storing messages within batches, and therefore it is recommended to use batching at the input level in high-throughput use cases even if they are not required for processing.

include::redpanda-connect:components:partial$fields/buffers/sqlite.adoc[]

nclude::redpanda-connect:components:partial$examples/buffers/sqlite.adoc[]

// end::single-source[]