= Introduction to Redpanda Connect
:page-aliases: guides:delivery_guarantee.adoc, ROOT:about.adoc

Redpanda Connect is a declarative connector framework that solves a wide range of data engineering problems with simple, chained, stateless xref:components:processors/about.adoc[processing steps]. It implements transaction-based resiliency with back pressure, so when connecting to at-least-once sources and sinks it's able to guarantee at-least-once delivery without needing to persist messages during transit.

It's xref:guides:getting_started.adoc[simple to deploy], comes with a wide range of xref:components:about.adoc[connectors], and is totally data agnostic, making it easy to drop into your existing infrastructure. Redpanda Connect has functionality that overlaps with integration frameworks, log aggregators and ETL workflow engines, and can therefore be used to complement these traditional data engineering tools or act as a simpler alternative.

== Next steps

- xref:guides:getting_started.adoc[Get started].
- xref:components:about.adoc[View all connectors]
