= Enterprise Licensing 
:description: Learn how to purchase and apply an Enterprise Edition license.

You need a valid Enterprise Edition license to use the following enterprise features:

enterprise_features::connect[]

== Get an enterprise license

You can either https://www.redpanda.com/upgrade[upgrade to an Enterprise Edition license^], or http://redpanda.com/try-enterprise[generate a trial license key^] that's valid for 30 days.


== Apply a license key to Redpanda Connect

When you have downloaded the license key, you can apply it using either the CLI (`rpk`) or Helm on Kubernetes.

[tabs]
======
rpk (local or VM)::
+
--
If you have a license key file, either:

- Save the license key to `/etc/redpanda/redpanda.license`.
- Set the environment variable `REDPANDA_LICENSE_FILEPATH` to point to the file where the license key is stored.

If you have a license string, either:

- Set the environment variable `REDPANDA_LICENSE` to the value of the full license string.
- Run the following command using the full license string:

```bash
rpk connect run --redpanda-license <license-string> ./<connect-configuration>.yaml
```

Replace the following placeholders:

  ** `<license-string>`: The full license key string.
  ** `<connect-configuration>`: The name of your Redpanda Connect configuration file.
--

Helm (Kubernetes)::
+
--
To enable enterprise features, you must provide a license key as a Kubernetes Secret and reference it in your deployment configuration.

. Create the Secret:
+
[source,bash]
----
kubectl create secret generic redpanda-connect-license \
  --from-literal=REDPANDA_LICENSE=<your-license-key> \
  --namespace <namespace>
----

. Reference the license secret in your `values.yaml` or as a Helm value:
+
[source,yaml]
----
envFrom:
  - secretRef:
      name: redpanda-connect-license
----

This configuration mounts the license key as the `REDPANDA_LICENSE` environment variable, allowing Redpanda Connect to use enterprise features.

--
======

== Verify a license

Redpanda Connect checks the license key status at runtime. If the license key is unavailable or has expired, you are blocked from using enterprise connectors.

You can view the license key’s expiration date at any time in the Redpanda Connect logs:

```
INFO Running main config from specified file       @service=benthos benthos_version=4.50.0 path=connect_2.yaml
INFO Successfully loaded Redpanda license          @service=benthos expires_at="2025-04-18T15:41:56+01:00" license_org=67XXX license_type="enterprise"
```

== Next steps

- xref:get-started:quickstarts/index.adoc[Get started with Redpanda Connect].
- xref:components:about.adoc[Explore enterprise connectors] to enhance your data pipelines.