= Enterprise Licensing 
:description: Learn how to purchase and apply an Enterprise Edition license.

You need a valid Enterprise Edition license to use the following enterprise features:

|===
| Feature | Description

| xref:configuration:allow_and_deny_lists.adoc[Allow or deny lists]
| Limit the Redpanda Connect components that users can run within data pipelines on a Redpanda Connect instance.

| xref:components:redpanda/about.adoc[Redpanda configuration service]
| A configuration block that you can use to send logs and status events to a topic on a Redpanda cluster.

| https://docs.redpanda.com/redpanda-connect/components/catalog/?support=enterprise[Redpanda enterprise connectors]
| Additional inputs, outputs, and processors available only to Enterprise customers.

| xref:configuration:secrets.adoc#look-up-secrets-on-a-remote-system-at-runtime[Secrets management]
| Retrieve secrets values from a remote system, such as a secret management solution, without setting environment variables.

|===

== Get an enterprise license

You can either https://www.redpanda.com/upgrade[upgrade to an Enterprise Edition license^], or http://redpanda.com/try-enterprise[generate a trial license key^] that's valid for 30 days.

== Apply a license key to Redpanda Connect

When you have downloaded the license key, you can apply it in the following ways: 

=== Apply the license using a license file

If you have a license key file, either:

- Save the license key to the following directory: `/etc/redpanda/redpanda.license`. 
- Set the environment variable: `$\{REDPANDA_LICENSE_FILEPATH}` to point to the file where the license key is stored.

=== Apply the license using an inline license string

If you do not have a license key file, run the following command using the full license string.

```bash
rpk connect run --redpanda-license <license-string> ./<connect-configuration>.yaml
```

Replace the following placeholders: 

- `<license-string>`: The full license key string.
- `<connect-configuration>`: The name of your Redpanda Connect configuration file.

== Verify a license

Redpanda Connect checks the license key status at runtime. If the license key is unavailable or has expired, you are blocked from using Enterprise connectors.

You can view the license key’s expiration date at any time in the Redpanda Connect logs.