= redpanda

component_type_dropdown::[]

// tag::single-source[]

// © 2024 Redpanda Data Inc.

You can configure Redpanda Connect to send logs and status updates to topics on a Redpanda cluster, in addition to the xref:components:logger/about.adoc[default logger]. The `redpanda` namespace contains the configuration of this service, which uses the following default values:

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
redpanda:
  pipeline_id: ""
  seed_brokers: [] # No default (optional)
  logs_topic: ""
  logs_level: info
  status_topic: ""
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
redpanda:
  pipeline_id: ""
  seed_brokers: [] # No default (optional)
  logs_topic: ""
  logs_level: info
  status_topic: ""
  client_id: benthos
  rack_id: ""
  timeout: 10s
  max_message_bytes: 1MB
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  sasl: [] # No default (optional)
```

--
======

== Fields

Schema properties for the `redpanda` section.

=== `pipeline_id`

The ID of a Redpanda Connect data pipeline (optional). When specified, the pipeline ID is written to all logs and status updates sent to the configured topics. 

*Type*: `string`

*Default*: `""`

=== `seed_brokers`

A list of broker addresses to connect to. List items that contain commas are expanded into multiple addresses.


*Type*: `array`


```yml
# Examples

seed_brokers:
  - localhost:9092

seed_brokers:
  - foo:9092
  - bar:9092

seed_brokers:
  - foo:9092,bar:9092
```

=== `logs_topic`

The topic that logs are sent to.

*Type*: `string`

*Default*: `""`

```yml
# Example

logs_topic: __redpanda.connect.logs
```

=== `logs_level`

The logging level of logs sent to Redpanda.

*Type*: `string`

*Default*: `info`

*Options*: `debug`, `info`, `warn`, `error`

=== `status_topic`

The topic that status updates are sent to. For full details of the schema for status updates, see the https://github.com/redpanda-data/connect/blob/main/internal/protoconnect/status.pb.go[object specification^].

*Type*: `string`

*Default*: `""`

```yml
# Example

status_topic: __redpanda.connect.status
```

=== `client_id`

An identifier for the client connection.

*Type*: `string`

*Default*: `benthos`

=== `rack_id`

A rack identifier for this client.

*Type*: `string`

*Default*: `""`

=== `timeout`

The maximum period of time allowed for sending log or status update messages before a request is abandoned and a retry attempted. 

*Type*: `string`

*Default*: `10s`

=== `max_message_bytes`

The maximum size of an individual message in bytes. Messages larger than this value are rejected. This field is equivalent to Kafka's `max.message.bytes`. 

*Type*: `string`

*Default*: `1MB`

```yml
# Examples

max_message_bytes: 100MB

max_message_bytes: 50mib
```

=== `tls`

You can use custom TLS settings to override system defaults.

*Type*: `object`


=== `tls.enabled`

Whether custom TLS settings are enabled.

*Type*: `bool`

*Default*: `false`

=== `tls.skip_cert_verify`

Whether to skip server-side certificate verification.

*Type*: `bool`

*Default*: `false`

=== `tls.enable_renegotiation`

Whether to allow the remote server to request renegotiation. Enable this option if you're seeing the error message `local error: tls: no renegotiation`.

*Type*: `bool`

*Default*: `false`

ifndef::env-cloud[]
Requires version 3.45.0 or newer
endif::[]

=== `tls.root_cas`

Specify a root certificate authority to use (optional). This is a string that represents a certificate chain from the parent trusted root certificate, through possible intermediate signing certificates, to the host certificate.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Example

root_cas: |-
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
```

=== `tls.root_cas_file`

Specify the path to a root certificate authority file (optional). This is a file, often with a `.pem` extension, which contains a certificate chain from the parent trusted root certificate, through possible intermediate signing certificates, to the host certificate.


*Type*: `string`

*Default*: `""`

```yml
# Example

root_cas_file: ./root_cas.pem
```

=== `tls.client_certs`

A list of client certificates to use. For each certificate, specify either the fields `cert` and `key` or `cert_file` and `key_file`.


*Type*: `array`

*Default*: `[]`

```yml
# Examples

client_certs:
  - cert: foo
    key: bar

client_certs:
  - cert_file: ./example.pem
    key_file: ./example.key
```

=== `tls.client_certs[].cert`

The plain text certificate to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key`

The plain text certificate key to use.

include::components:partial$secret_warning.adoc[]



*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].cert_file`

The path of a certificate to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key_file`

The path of a certificate key to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].password`

The plain text password for when the private key is password encrypted in PKCS#1 or PKCS#8 format. The obsolete `pbeWithMD5AndDES-CBC` algorithm is not supported for the PKCS#8 format. 

WARNING: The `pbeWithMD5AndDES-CBC` algorithm does not authenticate ciphertext, and is vulnerable to padding Oracle attacks which may allow an attacker recover the plain text password.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Examples

password: foo

password: ${KEY_PASSWORD}
```

=== `sasl`

Specify one or more methods or mechanisms of SASL authentication. They are tried in order. If the broker supports the first SASL mechanism, all connections use it. If the first mechanism fails, the client picks the first supported mechanism. If the broker does not support any client mechanisms, all connections fail.


*Type*: `array`


```yml
# Example

sasl:
  - mechanism: SCRAM-SHA-512
    password: bar
    username: foo
```

=== `sasl[].mechanism`

The SASL mechanism to use.


*Type*: `string`


|===
| Option | Summary
| `AWS_MSK_IAM`
| AWS IAM-based authentication as specified by the `aws-msk-iam-auth` Java library.
| `OAUTHBEARER`
| OAuth Bearer-based authentication.
| `PLAIN`
| Plain text authentication.
| `SCRAM-SHA-256`
| SCRAM-based authentication as specified in RFC5802.
| `SCRAM-SHA-512`
| SCRAM-based authentication as specified in RFC5802.
| `none`
| Disable SASL authentication

|===

=== `sasl[].username`

A username for `PLAIN` or `SCRAM-*` authentication.

*Type*: `string`

*Default*: `""`

=== `sasl[].password`

A password for `PLAIN` or `SCRAM-*` authentication.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

=== `sasl[].token`

The token to use for a single session's `OAUTHBEARER` authentication.


*Type*: `string`

*Default*: `""`

=== `sasl[].extensions`

Key/value pairs to add to `OAUTHBEARER` authentication requests.


=== `sasl[].aws`

AWS specific fields for when the `mechanism` is set to `AWS_MSK_IAM`.

*Type*: `object`

=== `sasl[].aws.region`

The AWS region to target.

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.endpoint`

Specify a custom endpoint for the AWS API.

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.credentials`

Manually configure the AWS credentials to use (optional). For more information, see the xref:guides:cloud/aws.adoc[Amazon Web Services guide].

*Type*: `object`

=== `sasl[].aws.credentials.profile`

The profile from `~/.aws/credentials` to use.

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.credentials.id`

The ID of the AWS credentials to use.

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.credentials.secret`

The secret for the AWS credentials in use.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.credentials.token`

The token for the AWS credentials in use. This is a required value for short-term credentials.

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.credentials.from_ec2_role`

Use the credentials of a host EC2 machine configured to assume an https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html[IAM role associated with the instance^].

*Type*: `bool`

*Default*: `false`

ifndef::env-cloud[]
Requires version 4.2.0 or newer
endif::[]

=== `sasl[].aws.credentials.role`

The role ARN to assume.

*Type*: `string`

*Default*: `""`

=== `sasl[].aws.credentials.role_external_id`

An external ID to use when assuming a role.

*Type*: `string`

*Default*: `""`

// end::single-source[]