= redpanda

component_type_dropdown::[]

As well as the xref:components:logger/about.adoc[default logger], you can configure Redpanda Connect to send logs to a topic in a Redpanda cluster.

The configuration for this feature lives under the `redpanda` namespace, with the following default values:

[source,yaml]
----
redpanda:
  seed_brokers: []
  logs_topic: __redpanda.connect.logs
  logs_level: info
  client_id: benthos
  rack_id: ""
  timeout: 10s
  max_message_bytes: 1MB
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  sasl: []
----


== Fields

=== `seed_brokers`

A list of broker addresses to connect to in order to establish connections. If an item of the list contains commas it will be expanded into multiple addresses.


*Type*: `array`


```yml
# Examples

seed_brokers:
  - localhost:9092

seed_brokers:
  - foo:9092
  - bar:9092

seed_brokers:
  - foo:9092,bar:9092
```

=== `logs_topic`

The topic to which logs will be sent.

*Type*: `string`

*Default*: `__redpanda.connect.logs`

=== `logs_level`

The log level for the logs sent to Redpanda. Possible values are `debug`, `info`, `warn`, `error`. Default is `info`.

*Type*: `string`

*Default*: `info`

=== `client_id`

An identifier for the client connection.


*Type*: `string`

*Default*: `"benthos"`

=== `rack_id`

A rack identifier for this client.


*Type*: `string`

*Default*: `""`

=== `timeout`

A duration string that determines the timeout for sending logs.

*Type*: `string`

*Default*: `10s`

=== `max_message_bytes`

The maximum size of a message to be sent to the logs topic.

*Type*: `int`

*Default*: `1048576` (1MB)

=== `tls`

Configuration for connecting to Redpanda cluster with TLS enabled.


*Type*: `object`


=== `tls.enabled`

Whether custom TLS settings are enabled.


*Type*: `bool`

*Default*: `false`

=== `tls.skip_cert_verify`

Whether to skip server side certificate verification.


*Type*: `bool`

*Default*: `false`

=== `tls.enable_renegotiation`

Whether to allow the remote server to repeatedly request renegotiation. Enable this option if you're seeing the error message `local error: tls: no renegotiation`.


*Type*: `bool`

*Default*: `false`

=== `tls.root_cas`

An optional root certificate authority to use. This is a string, representing a certificate chain from the parent trusted root certificate, to possible intermediate signing certificates, to the host certificate.

include::components:partial$secret_warning_sm.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Examples

root_cas: |-
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
```

=== `tls.root_cas_file`

An optional path of a root certificate authority file to use. This is a file, often with a .pem extension, containing a certificate chain from the parent trusted root certificate, to possible intermediate signing certificates, to the host certificate.


*Type*: `string`

*Default*: `""`

```yml
# Examples

root_cas_file: ./root_cas.pem
```

=== `tls.client_certs`

A list of client certificates to use. For each certificate either the fields `cert` and `key`, or `cert_file` and `key_file` should be specified, but not both.


*Type*: `array`

*Default*: `[]`

```yml
# Examples

client_certs:
  - cert: foo
    key: bar

client_certs:
  - cert_file: ./example.pem
    key_file: ./example.key
```

=== `tls.client_certs[].cert`

A plain text certificate to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key`

A plain text certificate key to use.

include::components:partial$secret_warning_sm.adoc[]



*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].cert_file`

The path of a certificate to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key_file`

The path of a certificate key to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].password`

A plain text password for when the private key is password encrypted in PKCS#1 or PKCS#8 format. The obsolete `pbeWithMD5AndDES-CBC` algorithm is not supported for the PKCS#8 format. Warning: Since it does not authenticate the ciphertext, it is vulnerable to padding oracle attacks that can let an attacker recover the plaintext.

include::components:partial$secret_warning_sm.adoc[]



*Type*: `string`

*Default*: `""`

```yml
# Examples

password: foo

password: ${KEY_PASSWORD}
```

=== `sasl`

Specify one or more methods of SASL authentication. SASL is tried in order; if the broker supports the first mechanism, all connections will use that mechanism. If the first mechanism fails, the client will pick the first supported mechanism. If the broker does not support any client mechanisms, connections will fail.


*Type*: `array`


```yml
# Examples

sasl:
  - mechanism: SCRAM-SHA-512
    password: bar
    username: foo
```

=== `sasl[].mechanism`

The SASL mechanism to use.


*Type*: `string`


|===
| Option | Summary

| `OAUTHBEARER`
| OAuth Bearer based authentication.
| `PLAIN`
| Plain text authentication.
| `SCRAM-SHA-256`
| SCRAM based authentication as specified in RFC5802.
| `SCRAM-SHA-512`
| SCRAM based authentication as specified in RFC5802.
| `none`
| Disable sasl authentication

|===

=== `sasl[].username`

A username to provide for PLAIN or SCRAM-* authentication.


*Type*: `string`

*Default*: `""`

=== `sasl[].password`

A password to provide for PLAIN or SCRAM-* authentication.

include::components:partial$secret_warning_sm.adoc[]

*Type*: `string`

*Default*: `""`

=== `sasl[].token`

The token to use for a single session's OAUTHBEARER authentication.


*Type*: `string`

*Default*: `""`

=== `sasl[].extensions`

Key/value pairs to add to OAUTHBEARER authentication requests.


*Type*: `object`