= Redpanda Connect Documentation
:url-playbook: https://github.com/redpanda-data/docs-site

image:https://img.shields.io/badge/slack-purple[Slack, link="https://redpanda.com/slack"]
image:https://img.shields.io/twitter/follow/redpandadata.svg?style=social&label=Follow[Twitter, link="https://twitter.com/intent/follow?screen_name=redpandadata"]

++++
<p>
<a href="https://docs.redpanda.com">
<object type="image/svg+xml">
  <img src="https://raw.githubusercontent.com/redpanda-data/docs-ui/main/src/img/redpanda-docs-logo.svg"/>
</object>
</p></a>
++++

This repository hosts the documentation content for Redpanda Connect.

== Contribute

The Redpanda docs are open source, and we welcome your contributions!

Before you add or edit content, consult the Redpanda https://github.com/redpanda-data/docs-site/blob/main/meta-docs/STYLE-GUIDE.adoc[Style Guide] for product documentation guidelines.

To contribute to the Redpanda docs, you have the following options:

|===
|Option|Description

|<<Open an issue>>
|Suggest a change by opening an issue on GitHub.

|<<Contribute content>>
|Make changes directly to the documentation and submit them through a pull request.

|===

=== Open an issue

The Redpanda docs team uses GitHub issues to track, plan, and prioritize tasks. To suggest changes, you can create an issue, which the team will then evaluate:

. Verify whether a similar issue already exists in that repository to avoid duplication.
. Go to **Issues** > **New Issue** to create a new issue.

You have the option to assign the issue to yourself or leave the assignee field blank. The Redpanda docs team triages all new issues and will allocate a writer if one isn't already assigned.

If you are a Redpanda employee, submit doc issues in `redpanda-data/documentation-private`.

=== Contribute content

You have two options to contribute to the documentation:

. Directly edit a page on GitHub by selecting **Make a contribution** > **Edit on GitHub** located at the bottom of a documentation page.
. Clone the docs repository to make changes locally on your machine. For a guide, see {url-playbook}/blob/main/meta-docs/CONTRIBUTING.adoc[Submit your first contribution].

Check the open docs issues. If you find an issue you'd like to work on:

- If the issue is already assigned to someone else, please consider another one.
- If the issue is unassigned, add a comment expressing your interest in working on it.

== Local development

If you want to run the website locally, install and update the packages:

```bash
npm update
```

Then, build the docs:

```bash
npm run build
```

This command generates static content in the `docs` directory and can be served using any hosting service.

You can serve the static files on a local web server using:

```bash
npm run serve
```

== Autogenerated docs

Some of the documentation files in this repository are autogenerated from the source code. These files include details about components, configurations, and usage that are derived from the codebase to ensure accuracy and consistency.

Autogenerated documentation files include a special comment at the top of the file:

[source,asciidoc]
----
////
     THIS FILE IS AUTOGENERATED!
////
----

The location of the source is included in this comment.