# tag::config[]
input:
  gcp_spanner_cdc:
    project_id: ${GCP_PROJECT_ID}
    instance_id: ${GCP_INSTANCE_ID}
    database_id: ${GCP_DATABASE_ID}
    stream_id: ${GCP_STREAM_ID}

pipeline:
  processors:
    - mapping: |
        root.mod_type = this.mod_type
        root.table_name = this.table_name
        root.commit_timestamp = this.commit_timestamp
        root.mods = this.mods
        root.transaction_id = this.server_transaction_id

output:
  stdout:
    codec: lines
# end::config[]
