= aws_kinesis_firehose
// tag::single-source[]
:page-commercial-names: Amazon Kinesis Firehose, AWS Kinesis Firehose, Kinesis Firehose
:type: output
:commercial-names: AWS Kinesis Firehose
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends messages to a Kinesis Firehose delivery stream.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/aws_kinesis_firehose.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/aws_kinesis_firehose.yaml[]
```

--
======

== Credentials

By default Redpanda Connect will use a shared credentials file when connecting to AWS services. It's also possible to set them explicitly at the component level, allowing you to transfer data across accounts. You can find out more in xref:guides:cloud/aws.adoc[].

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/aws_kinesis_firehose.adoc[]

// end::single-source[]