= aws_sqs
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends messages to an SQS queue.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
output:
  label: ""
  aws_sqs:
    url: "" # No default (required)
    message_group_id: "" # No default (optional)
    message_deduplication_id: "" # No default (optional)
    delay_seconds: "" # No default (optional)
    max_in_flight: 64
    metadata:
      exclude_prefixes: []
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
output:
  label: ""
  aws_sqs:
    url: "" # No default (required)
    message_group_id: "" # No default (optional)
    message_deduplication_id: "" # No default (optional)
    delay_seconds: "" # No default (optional)
    max_in_flight: 64
    metadata:
      exclude_prefixes: []
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
    max_records_per_request: 10
    region: ""
    endpoint: ""
    credentials:
      profile: ""
      id: ""
      secret: ""
      token: ""
      from_ec2_role: false
      role: ""
      role_external_id: ""
    max_retries: 0
    backoff:
      initial_interval: 1s
      max_interval: 5s
      max_elapsed_time: 30s
```

--
======

Metadata values are sent along with the payload as attributes with the data type String. If the number of metadata values in a message exceeds the message attribute limit (10) then the top ten keys ordered alphabetically will be selected.

The fields `message_group_id`, `message_deduplication_id` and `delay_seconds` can be set dynamically using xref:configuration:interpolation.adoc#bloblang-queries[function interpolations], which are resolved individually for each message of a batch.

== Credentials

By default Redpanda Connect will use a shared credentials file when connecting to AWS services. It's also possible to set them explicitly at the component level, allowing you to transfer data across accounts. You can find out more in xref:guides:cloud/aws.adoc[].

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/aws_sqs.adoc[]

// end::single-source[]