= aws_kinesis
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends messages to a Kinesis stream.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
output:
  label: ""
  aws_kinesis:
    stream: foo # No default (required)
    partition_key: "" # No default (required)
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
output:
  label: ""
  aws_kinesis:
    stream: foo # No default (required)
    partition_key: "" # No default (required)
    hash_key: "" # No default (optional)
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
    region: ""
    endpoint: ""
    credentials:
      profile: ""
      id: ""
      secret: ""
      token: ""
      from_ec2_role: false
      role: ""
      role_external_id: ""
    max_retries: 0
    backoff:
      initial_interval: 1s
      max_interval: 5s
      max_elapsed_time: 30s
```

--
======

Both the `partition_key`(required) and `hash_key` (optional) fields can be dynamically set using function interpolations described xref:configuration:interpolation.adoc#bloblang-queries[here]. When sending batched messages the interpolations are performed per message part.

== Credentials

By default Redpanda Connect will use a shared credentials file when connecting to AWS services. It's also possible to set them explicitly at the component level, allowing you to transfer data across accounts. You can find out more in xref:guides:cloud/aws.adoc[].

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/aws_kinesis.adoc[]

// end::single-source[]