= aws_s3
// tag::single-source[]
:page-commercial-names: Amazon S3, AWS S3, S3, Simple Storage Service
:type: output
:commercial-names: AWS S3
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Uploads messages to an Amazon S3 bucket as objects, using the path specified in the `path` field.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/aws_s3.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/aws_s3.yaml[]
```

--
======

To use a different path for each object, use xref:configuration:interpolation.adoc#bloblang-queries[function interpolation], which is evaluated for each message in a batch.

== Metadata

Redpanda Connect sends metadata fields as headers. To mutate or remove these values, see the xref:configuration:metadata.adoc[metadata docs].

== Tags

The `tags` field accepts key/value pairs to attach to objects as tags, and the values support xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions]:

```yaml
output:
  aws_s3:
    bucket: TODO
    path: ${!counter()}-${!timestamp_unix_nano()}.tar.gz
    tags:
      Key1: Value1
      Timestamp: ${!meta("Timestamp")}
```

=== Credentials

By default Redpanda Connect will use a shared credentials file when connecting to AWS services. It's also possible to set them explicitly at the component level, allowing you to transfer data across accounts. You can find out more in xref:guides:cloud/aws.adoc[].

== Batching

It's common to want to upload messages to S3 as batched archives. The easiest way to do this is to batch your messages at the output level and join the batch of messages with an xref:components:processors/archive.adoc[`archive`] or xref:components:processors/compress.adoc[`compress`] processor.

For example, the following configuration uploads messages as a .tar.gz archive of documents: 

```yaml
output:
  aws_s3:
    bucket: TODO
    path: ${!counter()}-${!timestamp_unix_nano()}.tar.gz
    batching:
      count: 100
      period: 10s
      processors:
        - archive:
            format: tar
        - compress:
            algorithm: gzip
```

Alternatively, this configuration uploads JSON documents as a single large document containing an array of objects:

```yaml
output:
  aws_s3:
    bucket: TODO
    path: ${!counter()}-${!timestamp_unix_nano()}.json
    batching:
      count: 100
      processors:
        - archive:
            format: json_array
```

== Bucket name format

The `bucket` field accepts a bucket name only, not an ARN. For example, use `my-bucket`, not `arn:aws:s3:::my-bucket`.

== S3-compatible storage

The `endpoint` and `force_path_style_urls` fields let you connect to S3-compatible storage services such as Cloudflare R2, MinIO, or DigitalOcean Spaces.

For Cloudflare R2, set `endpoint` to your account endpoint URL and enable `force_path_style_urls`:

```yaml
output:
  aws_s3:
    bucket: my-r2-bucket
    path: ${!uuid_v4()}.json
    endpoint: https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com
    force_path_style_urls: true
    region: auto
    credentials:
      id: YOUR_R2_ACCESS_KEY_ID
      secret: YOUR_R2_SECRET_ACCESS_KEY
```

Find your account endpoint URL in the Cloudflare dashboard under *R2 > Overview > Account Details*. Generate API credentials under *R2 > Manage R2 API Tokens*.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

include::redpanda-connect:components:partial$fields/outputs/aws_s3.adoc[]

// end::single-source[]