= azure_queue_storage
// tag::single-source[]
:type: output
:commercial-names: Azure Queue Storage
:status: beta
:categories: ["Services","Azure"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends messages to an Azure Storage Queue.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/azure_queue_storage.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/azure_queue_storage.yaml[]
```

--
======

Only one authentication method is required, `storage_connection_string` or `storage_account` and `storage_access_key`. If both are set then the `storage_connection_string` is given priority.

In order to set the `queue_name` you can use function interpolations described xref:configuration:interpolation.adoc#bloblang-queries[here], which are calculated per message of a batch.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/azure_queue_storage.adoc[]

// end::single-source[]