= azure_blob_storage
// tag::single-source[]
:page-commercial-names: Azure Blob Storage, Microsoft Azure Storage
:type: output
:status: beta
:categories: ["Services","Azure"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends message parts as objects to an Azure Blob Storage Account container. Each object is uploaded with the filename specified with the `container` field.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/azure_blob_storage.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/azure_blob_storage.yaml[]
```

--
======

In order to have a different path for each object you should use function
interpolations described xref:configuration:interpolation.adoc#bloblang-queries[here], which are
calculated per message of a batch.

Supports multiple authentication methods but only one of the following is required:

- `storage_connection_string`
- `storage_account` and `storage_access_key`
- `storage_account` and `storage_sas_token`
- `storage_account` to access via https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential[DefaultAzureCredential^]

If multiple are set then the `storage_connection_string` is given priority.

If the `storage_connection_string` does not contain the `AccountName` parameter, please specify it in the
`storage_account` field.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

include::redpanda-connect:components:partial$fields/outputs/azure_blob_storage.adoc[]

// end::single-source[]