= azure_table_storage
// tag::single-source[]
:type: output
:status: beta
:page-beta: true
:categories: ["Services","Azure"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Stores messages in an Azure Table Storage table.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
output:
  label: ""
  azure_table_storage:
    storage_account: ""
    storage_access_key: ""
    storage_connection_string: ""
    storage_sas_token: ""
    table_name: ${! meta("kafka_topic") } # No default (required)
    partition_key: ""
    row_key: ""
    properties: {}
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
output:
  label: ""
  azure_table_storage:
    storage_account: ""
    storage_access_key: ""
    storage_connection_string: ""
    storage_sas_token: ""
    table_name: ${! meta("kafka_topic") } # No default (required)
    partition_key: ""
    row_key: ""
    properties: {}
    transaction_type: INSERT
    max_in_flight: 64
    timeout: 5s
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
```

--
======

Only one authentication method is required, `storage_connection_string` or `storage_account` and `storage_access_key`. If both are set then the `storage_connection_string` is given priority.

In order to set the `table_name`,  `partition_key` and `row_key` you can use function interpolations described xref:configuration:interpolation.adoc#bloblang-queries[here], which are calculated per message of a batch.

If the `properties` are not set in the config, all the `json` fields are marshalled and stored in the table, which will be created if it does not exist.

The `object` and `array` fields are marshaled as strings. e.g.:

The JSON message:

```json
{
  "foo": 55,
  "bar": {
    "baz": "a",
    "bez": "b"
  },
  "diz": ["a", "b"]
}
```

Will store in the table the following properties:

```yml
foo: '55'
bar: '{ "baz": "a", "bez": "b" }'
diz: '["a", "b"]'
```

It's also possible to use function interpolations to get or transform the properties values, e.g.:

```yml
properties:
  device: '${! json("device") }'
  timestamp: '${! json("timestamp") }'
```

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/azure_table_storage.adoc[]

// end::single-source[]