= azure_data_lake_gen2
//tag::single-source[]
:type: output

:categories: ["Services","Azure"]


// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends message parts as files to an https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction[Azure Data Lake Gen2^] file system. Each file is uploaded with the file name specified in the `path` field.

ifndef::env-cloud[]
Introduced in version 4.38.0.
endif::[]


```yml
include::components:example$common/outputs/azure_data_lake_gen2.yaml[]
```

To specify a different <<path,`path` value>> (file name) for each file, use xref:configuration:interpolation.adoc#bloblang-queries[function
interpolations]. Function interpolations are calculated for each message in a batch.

== Authentication methods

This output supports multiple authentication methods. You must configure at least one method from the following list:

- `storage_connection_string`
- `storage_account` and `storage_access_key`
- `storage_account` and `storage_sas_token`
- `storage_account` to access using https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential[DefaultAzureCredential^]

If you configure multiple authentication methods, the `storage_connection_string` takes precedence.

== Performance

Sends multiple messages in flight in parallel for improved performance. You can tune the number of in flight messages (or message batches) with the field `max_in_flight`.

include::redpanda-connect:components:partial$fields/outputs/azure_data_lake_gen2.adoc[]

// end::single-source[]