= cache
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Stores each message in a xref:components:caches/about.adoc[cache].


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/cache.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/cache.yaml[]
```

--
======

Caches are configured as xref:components:caches/about.adoc[resources], where there's a wide variety to choose from.

:cache-support: aws_dynamodb=certified, aws_s3=certified, file=certified, memcached=certified, memory=certified, nats_kv=certified, redis=certified, ristretto=certified, couchbase=community, mongodb=community, sql=community, multilevel=community, ttlru=community, gcp_cloud_storage=community, lru=community, noop=community

The `target` field must reference a configured cache resource label like follows:

```yaml
output:
  cache:
    target: foo
    key: ${!json("document.id")}

cache_resources:
  - label: foo
    memcached:
      addresses:
        - localhost:11211
      default_ttl: 60s
```

In order to create a unique `key` value per item you should use function interpolations described in xref:configuration:interpolation.adoc#bloblang-queries[Bloblang queries].

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

include::redpanda-connect:components:partial$fields/outputs/cache.adoc[]

// end::single-source[]