= cassandra
:type: output
:commercial-names: Cassandra
:status: beta
:page-commercial-names: Apache Cassandra, Cassandra

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Runs a query against a Cassandra database for each message in order to insert data.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/cassandra.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/cassandra.yaml[]
```

--
======

Query arguments can be set using a bloblang array for the fields using the `args_mapping` field.

When populating timestamp columns the value must either be a string in ISO 8601 format (2006-01-02T15:04:05Z07:00), or an integer representing unix time in seconds.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$examples/outputs/cassandra.adoc[]

include::redpanda-connect:components:partial$fields/outputs/cassandra.adoc[]

