= cassandra
:type: output
:status: beta

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Runs a query against a Cassandra database for each message in order to insert data.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
output:
  label: ""
  cassandra:
    addresses: [] # No default (required)
    timeout: 600ms
    query: "" # No default (required)
    args_mapping: "" # No default (optional)
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
output:
  label: ""
  cassandra:
    addresses: [] # No default (required)
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    password_authenticator:
      enabled: false
      username: ""
      password: ""
    disable_initial_host_lookup: false
    max_retries: 3
    backoff:
      initial_interval: 1s
      max_interval: 5s
    timeout: 600ms
    query: "" # No default (required)
    args_mapping: "" # No default (optional)
    consistency: QUORUM
    logged_batch: true
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
```

--
======

Query arguments can be set using a bloblang array for the fields using the `args_mapping` field.

When populating timestamp columns the value must either be a string in ISO 8601 format (2006-01-02T15:04:05Z07:00), or an integer representing unix time in seconds.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$examples/outputs/cassandra.adoc[]

include::redpanda-connect:components:partial$fields/outputs/cassandra.adoc[]

