= elasticsearch_v9
// tag::single-source[]
:type: output
:status: stable
:categories: [Services]
:description: Publishes messages into an Elasticsearch index. If the index does not exist then it is created with a dynamic mapping.

component_type_dropdown::[]

Publishes messages into an Elasticsearch index. If the index does not exist then it is created with a dynamic mapping.



Both the `id` and `index` fields can be dynamically set using function interpolations described xref:configuration:interpolation.adoc#bloblang-queries[here]. When sending batched messages these interpolations are performed per message part.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/elasticsearch_v9.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/elasticsearch_v9.yaml[]
```

--
======

include::redpanda-connect:components:partial$fields/outputs/elasticsearch_v9.adoc[]

include::redpanda-connect:components:partial$examples/outputs/elasticsearch_v9.adoc[]


// end::single-source[]