= elasticsearch_v8
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Publishes messages into an https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html[Elasticsearch index^]. If the index does not exist, this output creates it using dynamic mapping.

NOTE: The `elasticsearch_v8` output is based on the the https://github.com/elastic/go-elasticsearch?tab=readme-ov-file[go-elasticsearch/v8] library. For full information about breaking changes from previous versions, see https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.0.html#breaking_80_rest_api_changes[Elastic's Migrating to 8.0 guide^]. 

To help configure your own `elasticsearch_v8` output, this page includes <<example-pipelines, example pipeline configurations>>.

ifndef::env-cloud[]
Introduced in version 4.47.0.
endif::[]


[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
output:
  label: ""
  elasticsearch_v8:
    urls: [] # No default (required)
    index: "" # No default (required)
    action: "" # No default (required)
    id: ${!counter()}-${!timestamp_unix()} # No default (required)
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: "" # Optional
      check: "" # Optional
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
output:
  label: ""
  elasticsearch_v8:
    urls: [] # No default (required)
    index: "" # No default (required)
    action: "" # No default (required)
    id: ${!counter()}-${!timestamp_unix()} # No default (required)
    pipeline: "" # Optional 
    routing: "" # Optional
    retry_on_conflict: 0
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: "" # Optional
      root_cas_file: "" # Optional
      client_certs: []
    max_in_flight: 64
    basic_auth:
      enabled: false
      username: ""
      password: ""
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
```

--
======

== Set values dynamically

You can use xref:configuration:interpolation.adoc#bloblang-queries[function interpolations] to dynamically set values for the <<id, `id`>> and <<index, `index`>> fields, as well as other fields where xref:configuration:interpolation.adoc#bloblang-queries[function interpolations] are supported. When message batches are sent, interpolations are performed per message.

== Performance

For improved performance, this output sends:

- Multiple messages in parallel. Adjust the `max_in_flight` field value to tune the maximum number of in-flight messages (or message batches). 
- Messages as batches. You can configure batches at both input and output level. For more information, see xref:configuration:batching.adoc[Message Batching].

include::redpanda-connect:components:partial$fields/outputs/elasticsearch_v8.adoc[]

== Example pipelines

[tabs]
======
Update documents::
+
--

To update documents in the target index, the top level of the request body must include at least one of the following fields:

- `doc`: Performs partial updates on a document.
- `upsert`: Updates an existing document or inserts a document if it doesn't exist.
- `script`: Performs an update using a scripting language, such as https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-painless.html[Elasticsearch's Painless scripting language^]. 

The following examples show how to configure mapping processors with this output to achieve different types of updates.
  
Example 1: Partial document update

```yaml
output:
  processors:
    # Sets the metadata ID field to the message ID then
    # performs a partial update on the document.
    - mapping: |
        meta id = this.id
        root.doc = this
  elasticsearch_v8:
    urls: [localhost:9200] # The URL of the Elasticsearch server.
    index: my_target_index # The name of the Elasticsearch index.
    id: ${! @id } # Sets the document ID to the value of the metadata ID field.
    action: update # The action to perform on each document.
```

Example 2: Scripted update

```yaml
output:
  processors:
    # Sets the metadata ID field to the message ID then 
    # increments the counter field by `1` using a script.
    - mapping: |
        meta id = this.id
        root.script.source = "ctx._source.counter += 1"
  elasticsearch_v8:
    urls: [localhost:9200] # The URL of the Elasticsearch server.
    index: my_target_index # The name of the Elasticsearch index.
    id: ${! @id } # Sets the document ID to the value of the metadata ID field.
    action: update # The action to perform on each document.
```

Example 3: Upsert

```yaml
output:
  processors:
    # Sets the metadata ID field to the message ID.
    # If the product with the specified ID exists, update its product_price to 100.
    # If the document does not exist, insert a new document with the ID set to 1 
    # and the `product_price` set to 50.
    - mapping: |     
        meta id = this.id
        root.doc.product_price = 100
        root.upsert.product_price = 50
  elasticsearch_v8:
    urls: [localhost:9200] # The URL of the Elasticsearch server.
    index: my_target_index # The name of the Elasticsearch index.
    id: ${! @id } # Sets the document ID to the value of the metadata ID field.
    action: update # The action to perform on each document.
```

For more information on the structures and behaviors of `doc`, `upsert`, and `script` fields, see the https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html[Elasticsearch Update API^].


--
Index documents from Redpanda::
+
--

Reads messages from a Redpanda cluster and writes them to an Elasticsearch index using a field from the message as the document ID.

```yaml
# Reads messages from a Redpanda cluster.
input:
  redpanda:
    seed_brokers: [localhost:19092] # The address of the Redpanda broker.
    topics: ["product_code"] # The topic to consume messages from.
    consumer_group: "rpcn3" # The consumer group ID.
  processors:
    # Sets the metadata ID field to the message ID and
    # sets the root of the message to the message content.
    - mapping: |
        meta id = this.id 
        root = this 
# Writes messages to the specified Elasticsearch index.
output:
  elasticsearch_v8:
    urls: ['http://localhost:9200'] # The URL of the Elasticsearch server.
    index: "product_code" # The name of the Elasticsearch index.
    action: "index" # The action to perform on each document. 
    id: ${! meta("id") } # Sets the document ID to the value of the metadata ID field. 
```

--
Index documents from AWS S3::
+
--

Reads messages from a AWS S3 bucket and writes them to an Elasticsearch index using the S3 key as the ID for the Elasticsearch document.

```yaml
# Reads messages from an AWS S3 bucket.
input:
  aws_s3:
    bucket: "my_bucket" # The name of the S3 bucket.
    prefix: "prod_inventory/" # A prefix to filter objects in the bucket.
    scanner:
      to_the_end: {} # Scans the bucket to the end.
# Writes messages to the specified Elasticsearch index.
output:
  elasticsearch_v8:
    urls: ['http://localhost:9200'] # The URL of the Elasticsearch server.
    index: "current_prod_inventory" # The name of the Elasticsearch index.
    action: "index" # The action to perform on each document.
    id: ${! meta("s3_key") } # Sets the document ID to the S3 key.
```

--
======


// end::single-source[]
