= gcp_pubsub
// tag::single-source[]
:page-commercial-names: Google Cloud Pub/Sub, GCP Pub/Sub, Google Pub/Sub
:type: output
:commercial-names: GCP Pub/Sub
:status: stable
:categories: ["Services","GCP"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends messages to a GCP Cloud Pub/Sub topic. xref:configuration:metadata.adoc[Metadata] from messages are sent as attributes.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/gcp_pubsub.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/gcp_pubsub.yaml[]
```

--
======

For information on how to set up credentials, see https://cloud.google.com/docs/authentication/production[this guide^].

== Troubleshooting

If you're consistently seeing `Failed to send message to gcp_pubsub: context deadline exceeded` error logs without any further information it is possible that you are encountering https://github.com/benthosdev/benthos/issues/1042, which occurs when metadata values contain characters that are not valid utf-8. This can frequently occur when consuming from Kafka as the key metadata field may be populated with an arbitrary binary value, but this issue is not exclusive to Kafka.

If you are blocked by this issue then a work around is to delete either the specific problematic keys:

```yaml
pipeline:
  processors:
    - mapping: |
        meta kafka_key = deleted()
```

Or delete all keys with:

```yaml
pipeline:
  processors:
    - mapping: meta = deleted()
```

include::redpanda-connect:components:partial$fields/outputs/gcp_pubsub.adoc[]

// end::single-source[]