= http_client
// tag::single-source[]
:type: output
:status: stable
:categories: ["Network"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sends messages to a HTTP server.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/http_client.yaml[]
```

--
Advanced::
+
--

ifndef::env-cloud[]
```yml
include::components:example$advanced/outputs/http_client.yaml[]
```
endif::[]
ifdef::env-cloud[]
```yml
# All configuration fields, showing default values
output:
  label: ""
  http_client:
    url: "" # No default (required)
    verb: POST
    headers: {}
    metadata:
      include_prefixes: []
      include_patterns: []
    dump_request_log_level: "" # Optional
    oauth:
      enabled: false
      consumer_key: "" # Optional
      consumer_secret: "" # Optional
      access_token: "" # Optional
      access_token_secret: "" # Optional
    oauth2:
      enabled: false
      client_key: "" # Optional
      client_secret: "" # Optional
      token_url: "" # Optional
      scopes: []
      endpoint_params: {}
    basic_auth:
      enabled: false
      username: "" # Optional
      password: "" # Optional
    jwt:
      enabled: false
      private_key_file: "" # Optional
      signing_method: "" # Optional
      claims: {}
      headers: {}
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    rate_limit: "" # No default (optional)
    timeout: 5s
    retry_period: 1s
    max_retry_backoff: 300s
    retries: 3
    backoff_on:
      - 429
    drop_on: []
    successful_on: []
    proxy_url: "" # No default (optional)
    batch_as_multipart: false
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: "" # Optional
      check: "" # Optional
      processors: [] # No default (optional)
    multipart: []
```
endif::[]
--
======

== Message sends

The body of the request sent to the HTTP server is the raw contents of the message payload. If the message has multiple parts (is a batch), the request is sent according to https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html[RFC1341^]. To disable this behavior, set the <<batch_as_multipart, `batch_as_multipart`>> field to `false`.

When message retries are exhausted, this output rejects a message. Typically, a pipeline then continues attempts to send the message until it succeeds, whilst applying back pressure.

== Dynamic URL and header settings

You can set the <<url,`url`>> and <<headers,`headers`>> values dynamically using xref:configuration:interpolation.adoc#bloblang-queries[function interpolations].


ifndef::env-cloud[]
== Propagate responses

To propagate HTTP responses back to the input source, set the <<propagate_response,`propagate_response`>> field to `true` . This feature is only available for inputs that support xref:guides:sync_responses.adoc[synchronous responses].

endif::[]

== Performance

For improved performance, this output sends:

- Multiple messages in parallel. Adjust the `max_in_flight` field value to tune the maximum number of in-flight messages (or message batches).
- Messages as batches. You can configure batches at both input and output level. For more information, see xref:configuration:batching.adoc[Message Batching].

include::redpanda-connect:components:partial$fields/outputs/http_client.adoc[]

// end::single-source[]