= kafka_franz
// tag::single-source[]
:page-commercial-names: Apache Kafka, Kafka
:type: output
:status: deprecated
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

[WARNING]
.Deprecated in 4.68.0
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto the unified xref:components:inputs/redpanda.adoc[`redpanda` input] and xref:components:outputs/redpanda.adoc[`redpanda` output] components.
====


The `kafka_franz` output writes a batch of messages to Kafka brokers and waits for acknowledgement before propagating any acknowledgments back to the input. This output often outperforms the traditional `kafka` output, as well as providing more useful logs and error messages.

This output uses the https://github.com/twmb/franz-go[Franz Kafka client library^].

ifndef::env-cloud[]
Introduced in version 3.61.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/kafka_franz.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/kafka_franz.yaml[]
```

--
======

include::redpanda-connect:components:partial$fields/outputs/kafka_franz.adoc[]

// end::single-source[]