= legacy_redpanda_migrator
// tag::single-source[]
:type: output
:status: deprecated
:categories: ["Services"]

component_type_dropdown::[]

[WARNING]
.Deprecated
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto the unified xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator` input] and xref:components:outputs/redpanda_migrator.adoc[`redpanda_migrator` output] components. For migration instructions, see xref:guides:migration/migrate-unified-redpanda-migrator.adoc[].
====

Writes a batch of messages to an Apache Kafka broker and waits for acknowledgement before propagating any acknowledgements back to the input.

Use this connector in conjunction with the xref:components:inputs/legacy_redpanda_migrator.adoc[`legacy_redpanda_migrator` input] to migrate topics between Kafka brokers. The `legacy_redpanda_migrator` output uses the https://github.com/twmb/franz-go[Franz Kafka client library^].

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/legacy_redpanda_migrator.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/legacy_redpanda_migrator.yaml[]
```

--
======

The default source for reading topics and access control lists (ACLs) is the <<input_resource,`input_resource`>>, which is set to `legacy_redpanda_migrator_input`. If your input uses a custom label, you must update this value.

When connected, this output queries the `legacy_redpanda_migrator` input for topic and ACL configurations. If the destination broker does not contain the topic in the current message, this output attempts to create the topic along with its ACLs. If the topic already exists on the broker, only missing ACLs are migrated.

ACL migration adheres to the following principles:

- `ALLOW WRITE` ACLs for topics are not migrated
- `ALLOW ALL` ACLs for topics are downgraded to `ALLOW READ`
- Only topic ACLs are migrated, group ACLs are not migrated

== Examples

=== Transfer data

Writes messages to the configured broker and creates topics and topic ACLs if they don't exist. It also ensures that the message order is preserved.

[source,yaml]
----
output:
  legacy_redpanda_migrator:
    seed_brokers: [ "127.0.0.1:9093" ]
    topic: ${! metadata("kafka_topic").or(throw("missing kafka_topic metadata")) }
    key: ${! metadata("kafka_key") }
    partitioner: manual
    partition: ${! metadata("kafka_partition").or(throw("missing kafka_partition metadata")) }
    timestamp_ms: ${! metadata("kafka_timestamp_ms").or(timestamp_unix_milli()) }
    input_resource: redpanda_migrator_input
    max_in_flight: 1
----

include::redpanda-connect:components:partial$fields/outputs/legacy_redpanda_migrator.adoc[]

// end::single-source[]
