= opensearch
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Publishes messages into an Elasticsearch index. If the index does not exist then it is created with a dynamic mapping.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
output:
  label: ""
  opensearch:
    urls: [] # No default (required)
    index: "" # No default (required)
    action: "" # No default (required)
    id: ${!counter()}-${!timestamp_unix()} # No default (required)
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
output:
  label: ""
  opensearch:
    urls: [] # No default (required)
    index: "" # No default (required)
    action: "" # No default (required)
    id: ${!counter()}-${!timestamp_unix()} # No default (required)
    pipeline: ""
    routing: ""
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    max_in_flight: 64
    basic_auth:
      enabled: false
      username: ""
      password: ""
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
    aws:
      enabled: false
      region: ""
      endpoint: ""
      credentials:
        profile: ""
        id: ""
        secret: ""
        token: ""
        from_ec2_role: false
        role: ""
        role_external_id: ""
```

--
======

Both the `id` and `index` fields can be dynamically set using function interpolations described xref:configuration:interpolation.adoc#bloblang-queries[here]. When sending batched messages these interpolations are performed per message part.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$examples/outputs/opensearch.adoc[]

include::redpanda-connect:components:partial$fields/outputs/opensearch.adoc[]

// end::single-source[]