= redis_hash
// tag::single-source[]
:page-commercial-names: Redis, Redis Hash
:type: output
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Sets Redis hash objects using the HMSET command.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/redis_hash.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/redis_hash.yaml[]
```

--
======

The field `key` supports xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions], allowing you to create a unique key for each message.

The field `fields` allows you to specify an explicit map of field names to interpolated values, also evaluated per message of a batch:

```yaml
output:
  redis_hash:
    url: tcp://localhost:6379
    key: ${!json("id")}
    fields:
      topic: ${!meta("kafka_topic")}
      partition: ${!meta("kafka_partition")}
      content: ${!json("document.text")}
```

If the field `walk_metadata` is set to `true` then Redpanda Connect will walk all metadata fields of messages and add them to the list of hash fields to set.

If the field `walk_json_object` is set to `true` then Redpanda Connect will walk each message as a JSON object, extracting keys and the string representation of their value and adds them to the list of hash fields to set.

The order of hash field extraction is as follows:

1. Metadata (if enabled)
2. JSON object (if enabled)
3. Explicit fields

Where latter stages will overwrite matching field names of a former stage.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

include::redpanda-connect:components:partial$fields/outputs/redis_hash.adoc[]

// end::single-source[]
