= redis_pubsub
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Publishes messages through the Redis PubSub model. It is not possible to guarantee that messages have been received.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/redis_pubsub.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/redis_pubsub.yaml[]
```

--
======

This output will interpolate functions within the channel field, you can find a list of functions xref:configuration:interpolation.adoc#bloblang-queries[here].

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/redis_pubsub.adoc[]

// end::single-source[]