= redis_list
// tag::single-source[]
:type: output
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Pushes messages onto the end of a Redis list (which is created if it doesn't already exist) using the RPUSH command.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/redis_list.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/redis_list.yaml[]
```

--
======

The field `key` supports xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions], allowing you to create a unique key for each message.

== Performance

This output benefits from sending multiple messages in flight in parallel for improved performance. You can tune the max number of in flight messages (or message batches) with the field `max_in_flight`.

This output benefits from sending messages as a batch for improved performance. Batches can be formed at both the input and output level. You can find out more xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/outputs/redis_list.adoc[]

// end::single-source[]