= redpanda_migrator_bundle
:page-aliases: components:outputs/kafka_migrator_bundle.adoc
// tag::single-source[]
:type: output
:page-beta: true
:categories: ["Services"]


// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

Writes messages and schemas to an Apache Kafka or Redpanda cluster. Use this output in conjunction with the xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator_bundle` input].

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]


```yml
# Config fields, showing default values
output:
  label: ""
  redpanda_migrator_bundle:
    redpanda_migrator: {} # No default (required)
    schema_registry: {} # No default (optional)
    translate_schema_ids: false
```

== Fields

=== `redpanda_migrator`

The xref:components:outputs/redpanda_migrator.adoc[`redpanda_migrator` output] configuration.

*Type*: `object`


=== `schema_registry`

The xref:components:outputs/schema_registry.adoc[`schema_registry` output] configuration. The `subject` field must be left empty.

*Type*: `object`

=== `translate_schema_ids`

When set to `true`, this field enables:

- The `translate_schema_ids` field in the specified xref:components:outputs/redpanda_migrator.adoc#translate_schema_ids[`redpanda_migrator` output].
- The `translate_ids` field in the specified xref:components:outputs/schema_registry.adoc#translate_ids[`schema_registry` output].

When set to `false`, both fields are disabled.

*Type*: `bool`

*Default*: `false`

// end::single-source[]
