= redpanda_migrator
:page-aliases: components:outputs/kafka_migrator.adoc
// tag::single-source[]
:type: output
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

Writes a batch of messages to an Apache Kafka broker and waits for acknowledgement before propagating any acknowledgements back to the input.

Use this connector in conjunction with the xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator` input] to migrate topics between Kafka brokers. The `redpanda_migrator` output uses the https://github.com/twmb/franz-go[Franz Kafka client library^].

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
output:
  label: ""
  redpanda_migrator:
    seed_brokers: [] # No default (required)
    topic: "" # No default (required)
    key: "" # No default (optional)
    partition: ${! meta("partition") } # No default (optional)
    metadata:
      include_prefixes: []
      include_patterns: []
    max_in_flight: 256
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
output:
  label: ""
  redpanda_migrator:
    seed_brokers: [] # No default (required)
    client_id: benthos
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    sasl: [] # No default (optional)
    topic: "" # No default (required)
    key: "" # No default (optional)
    partitioner: "" # No default (optional)
    partition: ${! meta("partition") } # No default (optional)
    metadata:
      include_prefixes: []
      include_patterns: []
    metadata_max_age: 5m
    request_timeout_overhead: 10s
    conn_idle_timeout: 20s
    timestamp_ms: ${! timestamp_unix_milli() } # No default (optional)
    topic_prefix: source. # No default (optional)
    max_in_flight: 256
    input_resource: redpanda_migrator_input
    replication_factor_override: true
    replication_factor: 3
    translate_schema_ids: false
    schema_registry_output_resource: schema_registry_output
    idempotent_write: true
    compression: "" # No default (optional)
    timeout: 10s
    max_message_bytes: 1MiB
    broker_write_max_bytes: 100MiB
```

--
======

The default source for reading topics and access control lists (ACLs) is the <<input_resource,`input_resource`>>, which is set to `redpanda_migrator_input`. If your input uses a custom label, you must update this value.

When connected, this output queries the `redpanda_migrator` input for topic and ACL configurations. If the destination broker does not contain the topic in the current message, this output attempts to create the topic along with its ACLs. If the topic already exists on the broker, only missing ACLs are migrated.

ACL migration adheres to the following principles:

- `ALLOW WRITE` ACLs for topics are not migrated
- `ALLOW ALL` ACLs for topics are downgraded to `ALLOW READ`
- Only topic ACLs are migrated, group ACLs are not migrated

include::redpanda-connect:components:partial$examples/outputs/redpanda_migrator.adoc[]

include::redpanda-connect:components:partial$fields/outputs/redpanda_migrator.adoc[]

// end::single-source[]
