= redpanda_migrator
:page-aliases: components:outputs/kafka_migrator.adoc
// tag::single-source[]
:type: output
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

Writes a batch of messages to an Apache Kafka broker and waits for acknowledgement before propagating any acknowledgements back to the input.

Use this connector in conjunction with the xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator` input] to migrate topics between Kafka brokers. The `redpanda_migrator` output uses the https://github.com/twmb/franz-go[Franz Kafka client library^].

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/outputs/redpanda_migrator.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/outputs/redpanda_migrator.yaml[]
```

--
======

The default source for reading topics and access control lists (ACLs) is the <<input_resource,`input_resource`>>, which is set to `redpanda_migrator_input`. If your input uses a custom label, you must update this value.

When connected, this output queries the `redpanda_migrator` input for topic and ACL configurations. If the destination broker does not contain the topic in the current message, this output attempts to create the topic along with its ACLs. If the topic already exists on the broker, only missing ACLs are migrated.

ACL migration adheres to the following principles:

- `ALLOW WRITE` ACLs for topics are not migrated
- `ALLOW ALL` ACLs for topics are downgraded to `ALLOW READ`
- Only topic ACLs are migrated, group ACLs are not migrated

include::redpanda-connect:components:partial$examples/outputs/redpanda_migrator.adoc[]

include::redpanda-connect:components:partial$fields/outputs/redpanda_migrator.adoc[]

// end::single-source[]
