= redpanda_migrator_bundle
:page-aliases: components:outputs/kafka_migrator_bundle.adoc
// tag::single-source[]
:type: output
:categories: ["Services"]
:status: deprecated

component_type_dropdown::[]

[WARNING]
.Deprecated in 4.67.5
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto the unified xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator` input] and xref:components:outputs/redpanda_migrator.adoc[`redpanda_migrator` output] components. For migration instructions, see xref:guides:migration/migrate-unified-redpanda-migrator.adoc[].
====

Writes messages and schemas to an Apache Kafka or Redpanda cluster. Use this output in conjunction with the xref:components:inputs/redpanda_migrator_bundle.adoc[`redpanda_migrator_bundle` input].

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]


```yml
# Config fields, showing default values
output:
  label: ""
  redpanda_migrator_bundle:
    redpanda_migrator: {} # No default (required)
    schema_registry: {} # No default (optional)
    translate_schema_ids: false
```

include::redpanda-connect:components:partial$fields/outputs/redpanda_migrator_bundle.adoc[]

// end::single-source[]
