= retry
// tag::single-source[]
:type: output
:status: stable
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Attempts to write messages to a child output and if the write fails for any reason the message is retried either until success or, if the retries or max elapsed time fields are non-zero, either is reached.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
output:
  label: ""
  retry:
    output: null # No default (required)
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
output:
  label: ""
  retry:
    max_retries: 0
    backoff:
      initial_interval: 500ms
      max_interval: 3s
      max_elapsed_time: 0s
    output: null # No default (required)
```

--
======

All messages in Redpanda Connect are always retried on an output error, but this would usually involve propagating the error back to the source of the message, whereby it would be reprocessed before reaching the output layer once again.

This output type is useful whenever we wish to avoid reprocessing a message on the event of a failed send. We might, for example, have a deduplication processor that we want to avoid reapplying to the same message more than once in the pipeline.

Rather than retrying the same output you may wish to retry the send using a different output target (a dead letter queue). In which case you should instead use the xref:components:outputs/fallback.adoc[`fallback`] output type.

include::redpanda-connect:components:partial$fields/outputs/retry.adoc[]

// end::single-source[]