= amqp_0_9
//tag::single-source[]
:type: input
:status: stable
:categories: ["Services"]


// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Connects to an AMQP (0.91) queue. AMQP is a messaging protocol used by various message brokers, including RabbitMQ.


[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
input:
  label: ""
  amqp_0_9:
    urls: [] # No default (required)
    queue: "" # No default (required)
    consumer_tag: "" # Optional
    prefetch_count: 10
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
input:
  label: ""
  amqp_0_9:
    urls: [] # No default (required)
    queue: "" # No default (required)
    queue_declare:
      enabled: false
      durable: true
      auto_delete: false
      arguments: {} # No default (optional)
    bindings_declare: [] # No default (optional)
    consumer_tag: "" # Optional
    auto_ack: false
    nack_reject_patterns: []
    prefetch_count: 10
    prefetch_size: 0
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: "" # Optional
      root_cas_file: "" # Optional
      client_certs: []
```

--
======

TLS is automatically enabled when connecting to an `amqps` URL. However, you can customize <<tls, TLS settings>> if required.

== Metadata

This input adds the following metadata fields to each message:

- `amqp_content_type`
- `amqp_content_encoding`
- `amqp_delivery_mode`
- `amqp_priority`
- `amqp_correlation_id`
- `amqp_reply_to`
- `amqp_expiration`
- `amqp_message_id`
- `amqp_timestamp`
- `amqp_type`
- `amqp_user_id`
- `amqp_app_id`
- `amqp_consumer_tag`
- `amqp_delivery_tag`
- `amqp_redelivered`
- `amqp_exchange`
- `amqp_routing_key`
- All existing message headers, including nested headers prefixed with the key of their respective parent.

You can access these metadata fields using xref:configuration:interpolation.adoc#bloblang-queries[function interpolations].

include::redpanda-connect:components:partial$fields/inputs/amqp_0_9.adoc[]

// end::single-source[]
