= aws_s3
// tag::single-source[]
:page-commercial-names: Amazon S3, AWS S3, S3, Simple Storage Service
:type: input
:commercial-names: AWS S3
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Downloads objects within an Amazon S3 bucket, optionally filtered by a prefix, either by walking the items in the bucket or by streaming upload notifications in real time.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/aws_s3.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/aws_s3.yaml[]
```

--
======

== Stream objects on upload with SQS

A common pattern for consuming S3 objects is to emit upload notification events from the bucket either directly to an SQS queue, or to an SNS topic that is consumed by an SQS queue, and then have your consumer listen for events that prompt it to download the newly uploaded objects. More information about this pattern and how to set it up can be found in the https://docs.aws.amazon.com/AmazonS3/latest/dev/ways-to-add-notification-config-to-bucket.html[Amazon S3 docs].

Redpanda Connect is able to follow this pattern when you configure an `sqs.url`, where it consumes events from SQS and downloads only the object keys contained in those events. For this to work, Redpanda Connect needs to know where within the event the key and bucket names can be found, specified as xref:configuration:field_paths.adoc[dot paths] with the fields `sqs.key_path` and `sqs.bucket_path`. The default values for these fields should already be correct when following the guide above.

If your notification events are being routed to SQS via an SNS topic, the events are enveloped by SNS, in which case you also need to specify the field `sqs.envelope_path`, which in the case of SNS to SQS will usually be `Message`.

When using SQS, make sure you have sensible values for `sqs.max_messages` and also the visibility timeout of the queue itself. When Redpanda Connect consumes an S3 object the SQS message that triggered it is not deleted until the S3 object has been sent onwards. This ensures at-least-once crash resiliency, but also means that if the S3 object takes longer to process than the visibility timeout of your queue, then the same objects might be processed multiple times.

== Download large files

When downloading large files, process them in streamed parts to avoid loading the entire file into memory at once. To do this, specify a <<scanner, `scanner`>> that determines how to break the input into smaller individual messages.

== Bucket and prefix

The `bucket` field accepts a bucket name only, not an ARN. For example, use `my-bucket`, not `arn:aws:s3:::my-bucket`.

The `prefix` field accepts a single string. To consume from multiple prefixes in the same bucket, use multiple `aws_s3` inputs in an xref:components:inputs/broker.adoc[`broker` input]:

```yaml
input:
  broker:
    inputs:
      - aws_s3:
          bucket: my-bucket
          prefix: logs/app1/
      - aws_s3:
          bucket: my-bucket
          prefix: logs/app2/
```

== Credentials

By default, Redpanda Connect uses a shared credentials file when connecting to AWS services. You can also set credentials explicitly at the component level to transfer data across accounts. You can find out more in xref:guides:cloud/aws.adoc[AWS credentials].

== S3-compatible storage

The `endpoint` and `force_path_style_urls` fields let you connect to S3-compatible storage services such as Cloudflare R2, MinIO, or DigitalOcean Spaces.

For Cloudflare R2, set `endpoint` to your account endpoint URL and enable `force_path_style_urls`:

```yaml
input:
  aws_s3:
    bucket: my-r2-bucket
    endpoint: https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com
    force_path_style_urls: true
    region: auto
    credentials:
      id: YOUR_R2_ACCESS_KEY_ID
      secret: YOUR_R2_SECRET_ACCESS_KEY
```

Find your account endpoint URL in the Cloudflare dashboard under *R2 > Overview > Account Details*. Generate API credentials under *R2 > Manage R2 API Tokens*.

== Metadata

This input adds the following metadata fields to each message:

- s3_key
- s3_bucket
- s3_last_modified_unix
- s3_last_modified (RFC3339)
- s3_content_type
- s3_content_encoding
- s3_version_id
- All user defined metadata

You can access these metadata fields using xref:configuration:interpolation.adoc#bloblang-queries[function interpolation]. User-defined metadata is case insensitive in AWS, so keys are often received in capitalized form. To normalize them, map all metadata keys to lowercase or uppercase using a Bloblang mapping such as `meta = meta().map_each_key(key -> key.lowercase())`.

include::redpanda-connect:components:partial$fields/inputs/aws_s3.adoc[]

// end::single-source[]