= aws_kinesis
// tag::single-source[]
:type: input
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Receive messages from one or more Kinesis streams.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
input:
  label: ""
  aws_kinesis:
    streams: [] # No default (required)
    dynamodb:
      table: ""
      create: false
    checkpoint_limit: 1024
    auto_replay_nacks: true
    commit_period: 5s
    start_from_oldest: true
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
input:
  label: ""
  aws_kinesis:
    streams: [] # No default (required)
    dynamodb:
      table: "" # No default (required)
      create: false
      billing_mode: PAY_PER_REQUEST
      read_capacity_units: 0
      write_capacity_units: 0
      credentials:
        profile: "" # No default (optional)
        id: "" # No default (optional)
        secret: "" # No default (optional)
        token: "" # No default (optional)
        from_ec2_role: false # No default (optional)
        role: "" # No default (optional)
        role_external_id: "" # No default (optional)
    checkpoint_limit: 1024
    auto_replay_nacks: true
    commit_period: 5s
    rebalance_period: 30s
    lease_period: 30s
    start_from_oldest: true
    region: "" # No default (optional)
    endpoint: "" # No default (optional)
    credentials:
      profile: "" # No default (optional)
      id: "" # No default (optional)
      secret: "" # No default (optional)
      token: "" # No default (optional)
      from_ec2_role: false
      role: "" # No default (optional)
      role_external_id: "" # No default (optional)
    batching:
      count: 0
      byte_size: 0
      period: "" # No default (optional)
      check: "" # No default (optional)
      processors: [] # No default (optional)
```

--
======

Consumes messages from one or more Kinesis streams either by automatically balancing shards across other instances of this input, or by consuming shards listed explicitly. The latest message sequence consumed by this input is stored within a <<table-schema,DynamoDB table>>, which allows it to resume at the correct sequence of the shard during restarts. This table is also used for coordination across distributed inputs when shard balancing.

Redpanda Connect will not store a consumed sequence unless it is acknowledged at the output level, which ensures at-least-once delivery guarantees.

== Ordering

By default messages of a shard can be processed in parallel, up to a limit determined by the field `checkpoint_limit`. However, if strict ordered processing is required then this value must be set to 1 in order to process shard messages in lock-step. When doing so it is recommended that you perform batching at this component for performance as it will not be possible to batch lock-stepped messages at the output level.

== Table schema

It's possible to configure Redpanda Connect to create the DynamoDB table required for coordination if it does not already exist. However, if you wish to create this yourself (recommended) then create a table with a string HASH key `StreamID` and a string RANGE key `ShardID`.

== Batching

Use the `batching` fields to configure an optional xref:configuration:batching.adoc#batch-policy[batching policy]. Each stream shard will be batched separately in order to ensure that acknowledgements aren't contaminated.

include::redpanda-connect:components:partial$fields/inputs/aws_kinesis.adoc[]

// end::single-source[]