= aws_kinesis
// tag::single-source[]
:page-commercial-names: Amazon Kinesis, AWS Kinesis, Kinesis
:type: input
:status: stable
:categories: ["Services","AWS"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Receive messages from one or more Kinesis streams.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/aws_kinesis.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/aws_kinesis.yaml[]
```

--
======

Consumes messages from one or more Kinesis streams either by automatically balancing shards across other instances of this input, or by consuming shards listed explicitly. The latest message sequence consumed by this input is stored within a <<table-schema,DynamoDB table>>, which allows it to resume at the correct sequence of the shard during restarts. This table is also used for coordination across distributed inputs when shard balancing.

Redpanda Connect will not store a consumed sequence unless it is acknowledged at the output level, which ensures at-least-once delivery guarantees.

== Ordering

By default messages of a shard can be processed in parallel, up to a limit determined by the field `checkpoint_limit`. However, if strict ordered processing is required then this value must be set to 1 in order to process shard messages in lock-step. When doing so it is recommended that you perform batching at this component for performance as it will not be possible to batch lock-stepped messages at the output level.

== Table schema

It's possible to configure Redpanda Connect to create the DynamoDB table required for coordination if it does not already exist. However, if you wish to create this yourself (recommended) then create a table with a string HASH key `StreamID` and a string RANGE key `ShardID`.

== Batching

Use the `batching` fields to configure an optional xref:configuration:batching.adoc#batch-policy[batching policy]. Each stream shard will be batched separately in order to ensure that acknowledgements aren't contaminated.

include::redpanda-connect:components:partial$fields/inputs/aws_kinesis.adoc[]

// end::single-source[]