= azure_cosmosdb
// tag::single-source[]
:page-commercial-names: Microsoft Azure, Azure
:type: input
:status: experimental
:categories: ["Azure"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Executes a SQL query against https://learn.microsoft.com/en-us/azure/cosmos-db/introduction[Azure CosmosDB^] and creates a batch of messages from each page of items.

ifndef::env-cloud[]
Introduced in version v4.25.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/azure_cosmosdb.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/azure_cosmosdb.yaml[]
```

--
======

== Cross-partition queries

Cross-partition queries are currently not supported by the underlying driver. For every query, the PartitionKey values must be known in advance and specified in the config. https://github.com/Azure/azure-sdk-for-go/issues/18578#issuecomment-1222510989[See details^].


== Credentials

You can use one of the following authentication mechanisms:

- Set the `endpoint` field and the `account_key` field
- Set only the `endpoint` field to use https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential[DefaultAzureCredential^]
- Set the `connection_string` field


== Metadata

This component adds the following metadata fields to each message:
```
- activity_id
- request_charge
```

You can access these metadata fields using xref:configuration:interpolation.adoc#bloblang-queries[function interpolation].

include::redpanda-connect:components:partial$examples/inputs/azure_cosmosdb.adoc[]

include::redpanda-connect:components:partial$fields/inputs/azure_cosmosdb.adoc[]

== CosmosDB emulator

If you wish to run the CosmosDB emulator that is referenced in the documentation https://learn.microsoft.com/en-us/azure/cosmos-db/linux-emulator[here^], the following Docker command should do the trick:

```bash
> docker run --rm -it -p 8081:8081 --name=cosmosdb -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
```

Note: `AZURE_COSMOS_EMULATOR_PARTITION_COUNT` controls the number of partitions that will be supported by the emulator. The bigger the value, the longer it takes for the container to start up.

Additionally, instead of installing the container self-signed certificate which is exposed via `https://localhost:8081/_explorer/emulator.pem`, you can run https://mitmproxy.org/[mitmproxy^] like so:

```bash
> mitmproxy -k --mode "reverse:https://localhost:8081"
```

Then you can access the CosmosDB UI via `http://localhost:8080/_explorer/index.html` and use `http://localhost:8080` as the CosmosDB endpoint.

// end::single-source[]