= csv
:type: input
:status: stable
:categories: ["Local"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Reads one or more CSV files as structured records following the format described in RFC 4180.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/csv.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/csv.yaml[]
```

--
======

This input offers more control over CSV parsing than the xref:components:inputs/file.adoc[`file` input].

When parsing with a header row each line of the file will be consumed as a structured object, where the key names are determined from the header now. For example, the following CSV file:

```csv
foo,bar,baz
first foo,first bar,first baz
second foo,second bar,second baz
```

Would produce the following messages:

```json
{"foo":"first foo","bar":"first bar","baz":"first baz"}
{"foo":"second foo","bar":"second bar","baz":"second baz"}
```

If, however, the field `parse_header_row` is set to `false` then arrays are produced instead, like follows:

```json
["first foo","first bar","first baz"]
["second foo","second bar","second baz"]
```

== Metadata

This input adds the following metadata fields to each message:

```text
- header
- path
- mod_time_unix
- mod_time (RFC3339)
```

You can access these metadata fields using xref:configuration:interpolation.adoc#bloblang-queries[function interpolation].

Note: The `header` field is only set when `parse_header_row` is `true`.

=== Output CSV column order

When xref:guides:bloblang/advanced.adoc#creating-csv[creating CSV] from Redpanda Connect messages, the columns must be sorted lexicographically to make the output deterministic. Alternatively, when using the `csv` input, one can leverage the `header` metadata field to retrieve the column order:

```yaml
input:
  csv:
    paths:
      - ./foo.csv
      - ./bar.csv
    parse_header_row: true

  processors:
    - mapping: |
        map escape_csv {
          root = if this.re_match("[\"\n,]+") {
            "\"" + this.replace_all("\"", "\"\"") + "\""
          } else {
            this
          }
        }

        let header = if count(@path) == 1 {
          @header.map_each(c -> c.apply("escape_csv")).join(",") + "\n"
        } else { "" }

        root = $header + @header.map_each(c -> this.get(c).string().apply("escape_csv")).join(",")

output:
  file:
    path: ./output/${! @path.filepath_split().index(-1) }
```

include::redpanda-connect:components:partial$fields/inputs/csv.adoc[]

