= gcp_spanner_cdc
// tag::single-source[]
:type: input
:status: beta
:categories: [Services, GCP]
:description: Creates an input that consumes from a spanner change stream.

component_type_dropdown::[]

Creates an input that consumes from a spanner change stream.

ifndef::env-cloud[]
Introduced in version 4.56.0.
endif::[]

[tabs]
======
Common::
+
--
```yaml
include::components:example$common/inputs/gcp_spanner_cdc.yaml[]
```
--
Advanced::
+
--
```yaml
include::components:example$advanced/inputs/gcp_spanner_cdc.yaml[]
```
--
======


Consumes change records from a Google Cloud Spanner change stream. This input allows
you to track and process database changes in real-time, making it useful for data
replication, event-driven architectures, and maintaining derived data stores.

The input reads from a specified change stream within a Spanner database and converts
each change record into a message. The message payload contains the change records in
JSON format, and metadata is added with details about the Spanner instance, database,
and stream.

Change streams provide a way to track mutations to your Spanner database tables. For
more information about Spanner change streams, refer to the link:https://cloud.google.com/spanner/docs/change-streams[Google Cloud documentation^].


include::redpanda-connect:components:partial$fields/inputs/gcp_spanner_cdc.adoc[]


// end::single-source[]