= http_client
// tag::single-source[]
:page-commercial-names: HTTP, REST API, REST
:type: input
:status: stable
:categories: ["Network"]

component_type_dropdown::[]

Connects to a server and continuously requests single messages.

[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/http_client.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/http_client.yaml[]
```

--
======

== Dynamic URL and header settings

You can set the <<url,`url`>> and <<headers,`headers`>> values dynamically using xref:configuration:interpolation.adoc#bloblang-queries[function interpolations].

=== Pagination

You can also add xref:configuration:interpolation.adoc#bloblang-queries[function interpolations] to the <<url,`url`>> and <<headers,`headers`>> fields to implement basic pagination, such as page numbers or tokens, where subsequent requests need to include data from previously-consumed responses.

Example:


```yaml
input:
  http_client:
    url: >-
      https://api.example.com/search?query=allmyfoos&start_time=${! (
        (timestamp_unix()-300).ts_format("2006-01-02T15:04:05Z","UTC").escape_url_query()
      ) }${! ("&next_token="+this.meta.next_token.not_null()) | "" }
    verb: GET
    rate_limit: schedule_searches
    oauth2:
      enabled: true
      token_url: https://api.example.com/oauth2/token
      client_key: "${EXAMPLE_KEY}"
      client_secret: "${EXAMPLE_SECRET}"

rate_limit_resources:
  - label: schedule_searches
    local:
      count: 1
      interval: 30s
```

TIP: If pagination requires more complex logic, consider using the xref:components:processors/http.adoc[`http` processor] combined with a xref:components:inputs/generate.adoc[`generate` input], which allows you to schedule the processor.

== Streaming messages

If you <<stream-enabled,enable streaming>>, Redpanda Connect consumes the body of the server response as a continuous stream of data, and breaks the stream down into smaller, logical messages using the <<stream-scanner,specified scanner>>. This functionality allows you to consume APIs that provide long-lived streamed data feeds, such as stock market feeds.

include::redpanda-connect:components:partial$fields/inputs/http_client.adoc[]

// end::single-source[]