= kafka_franz
// tag::single-source[]
:type: input
:commercial-names: Franz-go
:status: deprecated
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

[WARNING]
.Deprecated in 4.68.0
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto the unified xref:components:inputs/redpanda.adoc[`redpanda` input] and xref:components:outputs/redpanda.adoc[`redpanda` output] components.
====

A Kafka input using the https://github.com/twmb/franz-go[Franz Kafka client library^].

ifndef::env-cloud[]
Introduced in version 3.61.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/kafka_franz.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/kafka_franz.yaml[]
```

--
======

When you specify a consumer group in your configuration, this input consumes one or more topics and automatically balances the topic partitions across any other connected clients with the same consumer group. Otherwise, topics are consumed in their entirety or with explicit partitions.

This input often out-performs the traditional `kafka` input and provides more useful logs and error messages.

== Metadata

This input adds the following metadata fields to each message:

```text
- kafka_key
- kafka_topic
- kafka_partition
- kafka_offset
- kafka_timestamp_ms
- kafka_timestamp_unix
- kafka_tombstone_message
- All record headers
```

include::redpanda-connect:components:partial$fields/inputs/kafka_franz.adoc[]

// end::single-source[]