= legacy_redpanda_migrator_offsets
// tag::single-source[]
:type: input
:status: deprecated
:categories: ["Services"]
:page-aliases: components:inputs/redpanda_migrator_offsets.adoc

component_type_dropdown::[]

[WARNING]
.Deprecated in 4.67.5
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto the unified xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator` input] and xref:components:outputs/redpanda_migrator.adoc[`redpanda_migrator` output] components. For migration instructions, see xref:guides:migration/migrate-unified-redpanda-migrator.adoc[].
====

Reads consumer group offsets for a specified set of topics using the https://github.com/twmb/franz-go[Franz Kafka client library^]. 

ifndef::env-cloud[]
Introduced in version 4.45.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/legacy_redpanda_migrator_offsets.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/legacy_redpanda_migrator_offsets.yaml[]
```

--
======

== Metadata

This input adds the following metadata fields to each message:

- `kafka_key`
- `kafka_topic`
- `kafka_partition`
- `kafka_offset`
- `kafka_timestamp_unix`
- `kafka_timestamp_ms`
- `kafka_tombstone_message`
- `kafka_offset_topic`
- `kafka_offset_group`
- `kafka_offset_partition`
- `kafka_offset_commit_timestamp`
- `kafka_offset_metadata`
- `kafka_is_high_watermark`

include::redpanda-connect:components:partial$fields/inputs/legacy_redpanda_migrator_offsets.adoc[]

// end::single-source[]
