= mongodb_cdc
// tag::single-source[]
:type: input
:categories: ["Services"]

component_type_dropdown::[]

Streams data changes from a MongoDB replica set, using MongoDB's https://www.mongodb.com/docs/manual/changeStreams/[change streams^] to capture data updates.

ifndef::env-cloud[]
Introduced in version 4.48.1.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/mongodb_cdc.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/mongodb_cdc.yaml[]
```

--
======

== Prerequisites

- MongoDB version 6 or later
ifndef::env-cloud[]
- Network access from the cluster where your Redpanda Connect pipeline is running to the source database environment.
endif::[]
ifdef::env-cloud[]
- Network access from the cluster where your Redpanda Connect pipeline is running to the source database environment. For detailed networking information, including how to set up a VPC peering connection, see xref:networking:index.adoc[Redpanda Cloud Networking].
endif::[]
- A MongoDB database running as a https://www.mongodb.com/docs/manual/replication/#replication-in-mongodb[replica set^] or in a https://www.mongodb.com/docs/manual/sharding/[sharded cluster^] using replica set https://www.mongodb.com/docs/manual/reference/replica-configuration/#rsconf.protocolVersion[protocol version 1].
- A MongoDB database using the https://www.mongodb.com/docs/manual/core/wiredtiger/#storage-wiredtiger[WiredTiger] storage engine.


ifndef::env-cloud[]
== Enable connectivity from cloud-based data sources

To establish a secure connection between a cloud-based data source and Redpanda Connect, you must add the IP addresses of your Redpanda Connect instances to your firewall rules.

endif::[]

ifdef::env-cloud[]

== Enable connectivity from cloud-based data sources (BYOC)

To establish a secure connection between a cloud-based data source and Redpanda Connect, you must add the NAT Gateway IP address of your Redpanda cluster to the allowlist of your data source.

endif::[]

== Data capture method

The `mongodb_cdc` input uses https://www.mongodb.com/docs/manual/changeStreams/[change streams^] to capture data changes, which does not propagate _all_ changes to Redpanda Connect. To capture all changes in a MongoDB cluster, including deletions, enable pre- and post-image saving for the cluster and <<collections,required collections>>. For more information, see <<document_mode,`document_mode` options>> and the https://www.mongodb.com/docs/manual/changeStreams/#change-streams-with-document-pre--and-post-images[MongoDB documentation].


== Data replication

Redpanda Connect allows you to specify which <<collections,database collections>> in your source database to receive changes from.

You can also run the `mongodb_cdc` input in one of two modes, depending on whether you need a snapshot of existing data before streaming updates.

- Snapshot mode: Redpanda Connect first captures a snapshot of all data in the selected collections and streams the contents before processing changes from the last recorded https://www.mongodb.com/docs/manual/core/replica-set-oplog/[operations log (oplog)^] position.
- Streaming mode: Redpanda Connect skips the snapshot and processes only the most recent data changes, starting from the latest oplog position.

=== Snapshot mode

If you set the <<stream_snapshot,`stream_snapshot` field>> to `true`, Redpanda Connect connects to your MongoDB database and does the following to capture a snapshot of all data in the selected collections:

. Records the latest oplog position.
. Determines the strategy for splitting the snapshot data down into shards or chunks for more efficient processing:
.. If <<snapshot_auto_bucket_sharding,`snapshot_auto_bucket_sharding`>> is set to `false`, the internal `$splitVector` command is used to compute shards.  
.. If <<snapshot_auto_bucket_sharding,`snapshot_auto_bucket_sharding`>> is set to `true`, the https://www.mongodb.com/docs/manual/reference/operator/aggregation/bucketAuto/[`$bucketAuto`^] command is used instead. This setting is for environments, such as MongoDB Atlas, where the `$splitVector` command is not available.
. This input then uses the number of connections specified in <<snapshot_parallelism,`snapshot-parallelism`>> to read the selected collections.
+
NOTE: If the pipeline restarts during this process, Redpanda Connect must start the snapshot capture from scratch to store the current oplog position in the <<checkpoint_cache,`checkpoint_cache`>>.
. Finally, the input uses the stored oplog position to catch up with changes that occurred during snapshot processing.

=== Streaming mode

If you set the <<stream_snapshot,`stream_snapshot` field>> to `false`, Redpanda Connect connects to your MongoDB database and starts processing data changes from the latest oplog position. If the pipeline restarts, Redpanda Connect resumes processing updates from the last oplog position written to the <<checkpoint_cache,`checkpoint_cache`>>.

== Metadata

This input adds the following metadata fields to each message:

- `operation`: The type of data change that generated the message: `read`, `create`, `update`, `replace`, `delete`, `update`. A `read` operation occurs when the initial snapshot of the database is processed.
- `collection`: The name of the collection from which the message originated.
- `operation_time`: The time the data change was written to the https://www.mongodb.com/docs/manual/core/replica-set-oplog/[operations log (oplog)^] in the form of a Binary JSON (BSON) timestamp: `{"t": <unix seconds>, "i": <sequence number>}`.

include::redpanda-connect:components:partial$fields/inputs/mongodb_cdc.adoc[]

// end::single-source[]
