= nats_stream
:type: input
:status: stable
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Subscribe to a NATS Stream subject. Joining a queue is optional and allows multiple clients of a subject to consume using queue semantics.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
input:
  label: ""
  nats_stream:
    urls: [] # No default (required)
    cluster_id: "" # No default (required)
    client_id: ""
    queue: ""
    subject: ""
    durable_name: ""
    unsubscribe_on_close: false
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
input:
  label: ""
  nats_stream:
    urls: [] # No default (required)
    cluster_id: "" # No default (required)
    client_id: ""
    queue: ""
    subject: ""
    durable_name: ""
    unsubscribe_on_close: false
    start_from_oldest: true
    max_inflight: 1024
    ack_wait: 30s
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    auth:
      nkey_file: ./seed.nk # No default (optional)
      nkey: "" # No default (optional)
      user_credentials_file: ./user.creds # No default (optional)
      user_jwt: "" # No default (optional)
      user_nkey_seed: "" # No default (optional)
    extract_tracing_map: root = @ # No default (optional)
```

--
======

[CAUTION]
.Deprecation notice
====
The NATS Streaming Server is being deprecated. Critical bug fixes and security fixes will be applied until June of 2023. NATS-enabled applications requiring persistence should use https://docs.nats.io/nats-concepts/jetstream[JetStream^].
====

Tracking and persisting offsets through a durable name is also optional and works with or without a queue. If a durable name is not provided then subjects are consumed from the most recently published message.

When a consumer closes its connection, it unsubscribes from the subject. When all consumers of a durable queue do this, the offsets are deleted from the NATS server. To avoid this, set the `unsubscribe_on_close` field to `false`, to prevent consumers from unsubscribing.

== Metadata

This input adds the following metadata fields to each message:

- nats_stream_subject
- nats_stream_sequence

You can access these metadata fields using xref:configuration:interpolation.adoc#bloblang-queries[function interpolation].


== Authentication

There are a number of Redpanda Connect components that use NATS services. Each of these components
support optional, advanced authentication parameters for https://docs.nats.io/nats-server/configuration/securing_nats/auth_intro/nkey_auth[NKeys^] and https://docs.nats.io/using-nats/developer/connecting/creds[user credentials^].

For an in-depth guide, see the https://docs.nats.io/running-a-nats-service/nats_admin/security/jwt[NATS documentation^].

=== NKeys

NATS server can use NKeys in several ways for authentication. The simplest approach is to configure the server 
with a list of user's public keys. The server can then generate a challenge for each connection request from a client, and the client must respond to the challenge by signing it with its private NKey, configured in the `nkey_file` or `nkey` field.

For more details, see the https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/nkey_auth[NATS documentation^].

=== User credentials

NATS server also supports decentralized authentication based on JSON Web Tokens (JWTs). When a server is configured to use this authentication scheme, clients need a https://docs.nats.io/nats-server/configuration/securing_nats/jwt#json-web-tokens[user JWT^]
and a corresponding https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/nkey_auth[NKey secret^] to connect.

You can use either of the following methods to supply the user JWT and NKey secret:

* In the `user_credentials_file` field, enter the path to a file containing both the private key and the JWT. You can generate the file using the https://docs.nats.io/nats-tools/nsc[nsc tool^].
* In the `user_jwt` field, enter a plain text JWT, and in the `user_nkey_seed` field, enter
the plain text NKey seed or private key.

For more details about authentication using JWTs, see the https://docs.nats.io/using-nats/developer/connecting/creds[NATS documentation^].

include::redpanda-connect:components:partial$fields/inputs/nats_stream.adoc[]

