= parquet
:type: input
:status: experimental
:categories: ["Local"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Reads and decodes https://parquet.apache.org/docs/[Parquet files^] into a stream of structured messages.

Introduced in version 4.8.0.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/parquet.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/parquet.yaml[]
```

--
======

This input uses https://github.com/parquet-go/parquet-go[https://github.com/parquet-go/parquet-go^], which is itself experimental. Therefore changes could be made into how this processor functions outside of major version releases.

By default any BYTE_ARRAY or FIXED_LEN_BYTE_ARRAY value will be extracted as a byte slice (`[]byte`) unless the logical type is UTF8, in which case they are extracted as a string (`string`).

When a value extracted as a byte slice exists within a document which is later JSON serialized by default it will be base 64 encoded into strings, which is the default for arbitrary data fields. It is possible to convert these binary values to strings (or other data types) using Bloblang transformations such as `root.foo = this.foo.string()` or `root.foo = this.foo.encode("hex")`, etc.

include::redpanda-connect:components:partial$fields/inputs/parquet.adoc[]

