= read_until
// tag::single-source[]
:type: input
:status: stable
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Reads messages from a child input until a consumed message passes a xref:guides:bloblang/about.adoc[Bloblang query], at which point the input closes. It is also possible to configure a timeout after which the input is closed if no new messages arrive in that period.

```yml
include::components:example$common/inputs/read_until.yaml[]
```

Messages are read continuously while the query check returns false, when the query returns true the message that triggered the check is sent out and the input is closed. Use this to define inputs where the stream should end once a certain message appears.

If the idle timeout is configured, the input will be closed if no new messages arrive after that period of time. Use this field if you want to empty out and close an input that doesn't have a logical end.

Sometimes inputs close themselves. For example, when the `file` input type reaches the end of a file it will shut down. By default this type will also shut down. If you wish for the input type to be restarted every time it shuts down until the query check is met then set `restart_input` to `true`.

== Metadata

A metadata key `benthos_read_until` containing the value `final` is added to the first part of the message that triggers the input to stop.

include::redpanda-connect:components:partial$fields/inputs/read_until.adoc[]

include::redpanda-connect:components:partial$examples/inputs/read_until.adoc[]

// end::single-source[]