= redpanda
// tag::single-source[]
:type: input
:categories: ["Services"]

component_type_dropdown::[]

Consumes topic data from one or more Kafka brokers.

ifndef::env-cloud[]
Introduced in version 4.39.0.

NOTE: If you intend to use multiple `redpanda` components in your data pipeline, which have a common set of credentials, consider using the xref:components:inputs/redpanda_common.adoc[`redpanda_common` input] and xref:components:outputs/redpanda_common.adoc[output] instead.
endif::[]


[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/redpanda.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/redpanda.yaml[]
```

--
======

== Consumer groups

When you specify a consumer group in your configuration, this input consumes one or more topics and automatically balances the topic partitions across any other connected clients with the same consumer group. Otherwise, topics are consumed in their entirety or with explicit partitions.

== Delivery guarantees

If you choose to use consumer groups, the offsets of records received by Redpanda Connect are committed automatically. In the event of restarts, this input uses the committed offsets to resume data consumption where it left off.

Redpanda Connect guarantees at-least-once delivery. Records are only confirmed as delivered when all downstream outputs that a record is routed to have also confirmed delivery.

== Ordering

To preserve the order of topic partitions:

* Records consumed from each partition are processed and delivered in the order that they are received
* Only one batch of records of a given partition is processed at a time

This approach means that although records from different partitions may be processed in parallel, records from the same partition are processed in sequential order.

=== Delivery errors

The order in which records are delivered may be disrupted by delivery errors and any error-handling mechanisms that start up. Redpanda Connect leans towards at-least-once delivery unless instructed otherwise, and this includes reattempting delivery of data when the ordering of that data is no longer guaranteed.

For example, a batch of records is sent to an output broker and only a subset of records are delivered. In this scenario, Redpanda Connect (by default) attempts to deliver the records that failed, even though these delivery failures may have been sent before records that were delivered successfully.

==== Use a fallback output

To prevent delivery errors from disrupting the order of records, you must specify a xref:components:outputs/fallback.adoc[`fallback`] output in your pipeline configuration. When adding a `fallback` output, it is good practice to set the `auto_retry_nacks` field to `false`. This also improves the throughput of your pipeline. 

For example, the following configuration includes a `fallback` output. If Redpanda Connect fails to write delivery errors to the `foo` topic, it then attempts to write them into a dead letter queue topic (`foo_dlq`), which is retried indefinitely as a way to apply back pressure.

```yaml
output:
  fallback:
    - redpanda_common:
        topic: foo
    - retry:
        output:
          redpanda_common:
            topic: foo_dlq
```
== Batching

Records are processed and delivered from each partition in the same batches as they are received from brokers. Batch sizes are dynamically sized in order to optimize throughput, but you can tune them further using the following configuration fields:

* `fetch_max_partition_bytes`
* `fetch_max_bytes`

You can break batches down further using the xref:components:processors/split.adoc[`split`] processor.

== Metrics

This input emits a `redpanda_lag` metric with `topic` and `partition` labels for each consumed topic. The metric records the number of produced messages that remain to be read from each topic/partition pair by the specified consumer group.

== Metadata

This input adds the following metadata fields to each message:

- `kafka_key`
- `kafka_topic`
- `kafka_partition`
- `kafka_offset`
- `kafka_lag`
- `kafka_timestamp_ms`
- `kafka_timestamp_unix`
- `kafka_tombstone_message`
- All record headers

include::redpanda-connect:components:partial$fields/inputs/redpanda.adoc[]

// end::single-source[]