= redpanda_migrator_bundle
:page-aliases: components:inputs/kafka_migrator_bundle.adoc
// tag::single-source[]
:type: input
:status: deprecated
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

[WARNING]
.Deprecated
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto the unified xref:components:inputs/redpanda_migrator.adoc[`redpanda_migrator` input] and xref:components:outputs/redpanda_migrator.adoc[`redpanda_migrator` output] components. For migration instructions, see xref:guides:migration/migrate-unified-redpanda-migrator.adoc[].
====

The `redpanda_migrator_bundle` input reads messages and schemas from an Apache Kafka or Redpanda cluster. Use this input in conjunction with the xref:components:outputs/redpanda_migrator_bundle.adoc[`redpanda_migrator_bundle` output].

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

```yml
# Config fields, showing default values
input:
  label: ""
  redpanda_migrator_bundle:
    redpanda_migrator: {} # No default (required)
    schema_registry: {} # No default (optional)
    migrate_schemas_before_data: true
```

include::redpanda-connect:components:partial$fields/inputs/redpanda_migrator_bundle.adoc[]

// end::single-source[]
