= redpanda_migrator
:page-aliases: components:inputs/kafka_migrator.adoc
// tag::single-source[]
:type: input
:page-beta: true
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

Use this connector in conjunction with the xref:components:outputs/redpanda_migrator.adoc[`redpanda_migrator` output] to migrate topics between Apache Kafka brokers. The `redpanda_migrator` input uses the https://github.com/twmb/franz-go[Franz Kafka client library^].


ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
input:
  label: ""
  redpanda_migrator:
    seed_brokers: [] # No default (required)
    topics: [] # No default (required)
    regexp_topics: false
    transaction_isolation_level: read_uncommitted
    consumer_group: "" # No default (optional)
    auto_replay_nacks: true
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
input:
  label: ""
  redpanda_migrator:
    seed_brokers: [] # No default (required)
    client_id: benthos
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: "" # No default (optional)
      root_cas_file: "" # No default (optional)
      client_certs: [] # No default (optional)
    sasl: [] # No default (optional)
    topics: [] # No default (required)
    regexp_topics: false
    rack_id: "" # No default (optional)
    instance_id: "" # No default (optional)
    rebalance_timeout: 45s
    session_timeout: 1m
    heartbeat_interval: 3s
    start_offset: earliest
    fetch_max_bytes: 50MiB
    fetch_max_wait: 5s
    fetch_min_bytes: 1B
    fetch_max_partition_bytes: 1MiB
    transaction_isolation_level: read_uncommitted
    consumer_group: "" # No default (optional)
    commit_period: 5s
    metadata_max_age: 5m
    request_timeout_overhead: 10s
    conn_idle_timeout: 20s
    partition_buffer_bytes: 1MB
    auto_replay_nacks: true
    topic_lag_refresh_period: 5s
    
```

--
======

The `redpanda_migrator` input:

* Reads a batch of messages from a Kafka broker.
* Waits for the `redpanda_migrator` output to acknowledge the writes before updating the Kafka consumer group offset.
* Provides the same delivery guarantees and ordering semantics as the xref:components:inputs/redpanda.adoc[`redpanda` input].

Specify a consumer group to make this input consume one or more topics and automatically balance the topic partitions across any other connected clients with the same consumer group. Otherwise, topics are consumed in their entirety or with explicit partitions.

== Metrics

This input emits an `input_redpanda_migrator_lag` metric with `topic` and `partition` labels for each consumed topic. The metric records the number of produced messages that remain to be read from each topic/partition pair by the specified consumer group.

== Metadata

This input adds the following metadata fields to each message:

```text
- kafka_key
- kafka_topic
- kafka_partition
- kafka_offset
- kafka_lag
- kafka_timestamp_ms
- kafka_timestamp_unix
- All record headers
```

include::redpanda-connect:components:partial$fields/inputs/redpanda_migrator.adoc[]

// end::single-source[]
