= slack_users
// tag::single-source[]
:type: input

component_type_dropdown::[]

Returns https://api.slack.com/methods/users.list#examples[the full profile^] of all users in a Slack organization using the Slack API method https://api.slack.com/methods/users.list[users.list^]. Optionally, you can filter the list of returned users by team ID.

This input is useful when you need to:

- Join user information to Slack posts.
- Ingest user information into a data lakehouse to create joins with other fields. 


ifndef::env-cloud[]
Introduced in version 4.52.0.
endif::[]

```yml
# Common configuration fields, showing default values
input:
  label: ""
  slack_users:
    bot_token: "" # No default (required)
    team_id: "" No default (optional)
    auto_replay_nacks: true
```

== Fields

=== `bot_token`

Your https://api.slack.com/concepts/token-types[Slack bot user's OAuth token^], which must have the https://api.slack.com/scopes/users:read[`users.read` scope^] to access your Slack organization.

*Type*: `string`

=== `team_id`

The encoded ID of a Slack team by which to filter the list of returned users, which you can get from the https://api.slack.com/methods/team.info[`team.info` Slack API method^]. If `team_id` is left empty, users from all teams within the organization are returned.

*Type*: `string`

*Default*: `""`

=== `auto_replay_nacks`

Whether to automatically replay messages that are rejected (nacked) at the output level. If the cause of rejections is persistent, leaving this option enabled can result in back pressure.

Set `auto_replay_nacks` to `false` to delete rejected messages. Disabling auto replays can greatly improve memory efficiency of high throughput streams, as the original shape of the data is discarded immediately upon consumption and mutation.

*Type*: `bool`

*Default*: `true`

// end::single-source[]