= subprocess
:type: input
:status: beta
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Executes a command, runs it as a subprocess, and consumes messages from it over stdout.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/inputs/subprocess.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/inputs/subprocess.yaml[]
```

--
======

Messages are consumed according to a specified codec. The command is executed once and if it terminates the input also closes down gracefully. Alternatively, the field `restart_on_close` can be set to `true` in order to have Redpanda Connect re-execute the command each time it stops.

The field `max_buffer` defines the maximum message size able to be read from the subprocess. This value should be set significantly above the real expected maximum message size.

The execution environment of the subprocess is the same as the Redpanda Connect instance, including environment variables and the current working directory.

include::redpanda-connect:components:partial$fields/inputs/subprocess.adoc[]

