= twitter_search
:type: input
:status: experimental
:categories: ["Services","Social"]


// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Consumes tweets matching a given search using the Twitter recent search V2 API.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
input:
  label: ""
  twitter_search:
    query: "" # No default (required)
    tweet_fields: []
    poll_period: 1m
    backfill_period: 5m
    cache: "" # No default (required)
    api_key: "" # No default (required)
    api_secret: "" # No default (required)
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
input:
  label: ""
  twitter_search:
    query: "" # No default (required)
    tweet_fields: []
    poll_period: 1m
    backfill_period: 5m
    cache: "" # No default (required)
    cache_key: last_tweet_id
    rate_limit: ""
    api_key: "" # No default (required)
    api_secret: "" # No default (required)
```

--
======

Continuously polls the https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent[Twitter recent search V2 API^] for tweets that match a given search query.

Each tweet received is emitted as a JSON object message, with a field `id` and `text` by default. Extra fields https://developer.twitter.com/en/docs/twitter-api/fields[can be obtained from the search API^] when listed with the `tweet_fields` field.

In order to paginate requests that are made the ID of the latest received tweet is stored in a xref:components:caches/about.adoc[cache resource], which is then used by subsequent requests to ensure only tweets after it are consumed. It is recommended that the cache you use is persistent so that Redpanda Connect can resume searches at the correct place on a restart.

Authentication is done using OAuth 2.0 credentials which can be generated within the https://developer.twitter.com[Twitter developer portal^].

include::redpanda-connect:components:partial$fields/inputs/twitter_search.adoc[]

