# tag::config[]
input:
  aws_dynamodb_cdc:
    table: ${DYNAMODB_TABLE}
    region: ${AWS_REGION}
    checkpoint_table: redpanda_dynamodb_checkpoints
    start_from: trim_horizon

pipeline:
  processors:
    # Extract the change event details
    - mapping: |
        root.event_type = this.eventName
        root.table = this.tableName
        root.event_id = this.eventID
        root.keys = this.dynamodb.keys
        root.new_image = this.dynamodb.newImage
        root.old_image = this.dynamodb.oldImage
        root.sequence_number = this.dynamodb.sequenceNumber
        root.timestamp = now()

output:
  stdout:
    codec: lines
# end::config[]

# tag::tests[]
tests:
  - name: Transform INSERT event
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          awsRegion: "us-east-1"
          dynamodb:
            keys:
              pk: "user#123"
              sk: "profile"
            newImage:
              pk: "user#123"
              sk: "profile"
              name: "Alice"
              email: "alice@example.com"
            sequenceNumber: "12345"
          eventID: "abc-123"
          eventName: "INSERT"
          tableName: "users"
    output_batches:
      - - json_contains:
            event_type: "INSERT"
            table: "users"
            event_id: "abc-123"
            keys:
              pk: "user#123"
              sk: "profile"
            new_image:
              name: "Alice"
              email: "alice@example.com"

  - name: Transform MODIFY event
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          awsRegion: "us-east-1"
          dynamodb:
            keys:
              pk: "user#123"
              sk: "profile"
            oldImage:
              pk: "user#123"
              sk: "profile"
              name: "Alice"
            newImage:
              pk: "user#123"
              sk: "profile"
              name: "Alice Smith"
            sequenceNumber: "12346"
          eventID: "abc-124"
          eventName: "MODIFY"
          tableName: "users"
    output_batches:
      - - json_contains:
            event_type: "MODIFY"
            table: "users"
            old_image:
              name: "Alice"
            new_image:
              name: "Alice Smith"

  - name: Transform REMOVE event
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          awsRegion: "us-east-1"
          dynamodb:
            keys:
              pk: "user#456"
              sk: "profile"
            oldImage:
              pk: "user#456"
              sk: "profile"
              name: "Bob"
            sequenceNumber: "12347"
          eventID: "abc-125"
          eventName: "REMOVE"
          tableName: "users"
    output_batches:
      - - json_contains:
            event_type: "REMOVE"
            table: "users"
            old_image:
              name: "Bob"
# end::tests[]
