# tag::config[]
input:
  aws_dynamodb_cdc:
    table: ${DYNAMODB_TABLE}
    region: ${AWS_REGION}

pipeline:
  processors:
    # Only process MODIFY events
    - mapping: |
        root = if this.eventName != "MODIFY" { deleted() } else { this }

    # Compare old and new images to find changed fields
    - mapping: |
        let old_data = this.dynamodb.oldImage
        let new_data = this.dynamodb.newImage

        root.table = this.tableName
        root.keys = this.dynamodb.keys
        root.timestamp = now()

        # Find fields that changed by comparing key-value pairs
        root.changes = $new_data.key_values().filter(kv -> !$old_data.exists(kv.key) || $old_data.get(kv.key) != kv.value).map_each(kv -> {"field": kv.key, "old_value": if $old_data.exists(kv.key) { $old_data.get(kv.key) } else { null }, "new_value": kv.value})

        # Find fields that were removed
        root.removed_fields = $old_data.keys().filter(k -> !$new_data.exists(k))

output:
  stdout:
    codec: lines
# end::config[]

# tag::tests[]
tests:
  - name: Filter out non-MODIFY events
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          eventName: "INSERT"
          dynamodb:
            keys:
              pk: "user#123"
            newImage:
              pk: "user#123"
    output_batches: []

  - name: Pass through MODIFY events
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          eventName: "MODIFY"
          dynamodb:
            keys:
              pk: "user#123"
            oldImage:
              pk: "user#123"
              name: "Alice"
            newImage:
              pk: "user#123"
              name: "Alice Smith"
    output_batches:
      - - json_contains:
            eventName: "MODIFY"

  - name: Detect changed fields
    target_processors: '/pipeline/processors/1'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          eventName: "MODIFY"
          tableName: "users"
          dynamodb:
            keys:
              pk: "user#123"
            oldImage:
              pk: "user#123"
              name: "Alice"
              status: "active"
            newImage:
              pk: "user#123"
              name: "Alice Smith"
              status: "active"
    output_batches:
      - - json_contains:
            table: "users"
            keys:
              pk: "user#123"
            changes:
              - field: "name"
                old_value: "Alice"
                new_value: "Alice Smith"
# end::tests[]
