# tag::config[]
input:
  aws_dynamodb_cdc:
    table: ${DYNAMODB_TABLE}
    region: ${AWS_REGION}
    start_from: latest

pipeline:
  processors:
    # Filter to only process INSERT and MODIFY events (ignore REMOVE)
    - mapping: |
        root = if this.eventName == "REMOVE" { deleted() } else { this }

    # Transform to a simplified format
    - mapping: |
        root.event_type = this.eventName
        root.keys = this.dynamodb.keys
        root.new_data = this.dynamodb.newImage
        root.old_data = this.dynamodb.oldImage

output:
  stdout:
    codec: lines
# end::config[]

# tag::tests[]
tests:
  - name: Filter out REMOVE events
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          eventName: "REMOVE"
          dynamodb:
            keys:
              pk: "user#456"
    output_batches: []

  - name: Pass through INSERT events
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          eventName: "INSERT"
          dynamodb:
            keys:
              pk: "user#123"
            newImage:
              pk: "user#123"
              name: "Alice"
    output_batches:
      - - json_contains:
            eventName: "INSERT"

  - name: Transform to simplified format
    target_processors: '/pipeline/processors/1'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
    input_batch:
      - json_content:
          eventName: "INSERT"
          dynamodb:
            keys:
              pk: "user#123"
              sk: "profile"
            newImage:
              pk: "user#123"
              sk: "profile"
              name: "Alice"
              age: 30
    output_batches:
      - - json_contains:
            event_type: "INSERT"
            keys:
              pk: "user#123"
              sk: "profile"
            new_data:
              name: "Alice"
              age: 30
# end::tests[]
