# tag::config[]
input:
  aws_dynamodb_cdc:
    table: ${DYNAMODB_TABLE}
    region: ${AWS_REGION}
    checkpoint_table: redpanda_dynamodb_checkpoints
    start_from: trim_horizon

pipeline:
  processors:
    # Add partitioning metadata for S3 organization
    - mapping: |
        let event_time = now()
        meta s3_path = "year=%s/month=%s/day=%s/hour=%s".format(
          $event_time.ts_format("2006"),
          $event_time.ts_format("01"),
          $event_time.ts_format("02"),
          $event_time.ts_format("15")
        )
        root.event_type = this.eventName
        root.table = this.tableName
        root.sequence_number = this.dynamodb.sequenceNumber
        root.event_time = $event_time
        root.keys = this.dynamodb.keys
        root.new_image = this.dynamodb.newImage
        root.old_image = this.dynamodb.oldImage

output:
  aws_s3:
    bucket: ${S3_BUCKET}
    path: dynamodb-cdc/${DYNAMODB_TABLE}/${! @s3_path }/${! uuid_v4() }.json
    region: ${AWS_REGION}
    batching:
      count: 1000
      period: 1m
      processors:
        - archive:
            format: lines
# end::config[]

# tag::tests[]
tests:
  - name: Add S3 partitioning metadata
    target_processors: '/pipeline/processors/0'
    environment:
      DYNAMODB_TABLE: test-table
      AWS_REGION: us-east-1
      S3_BUCKET: test-bucket
    input_batch:
      - json_content:
          eventName: "INSERT"
          tableName: "sensor_data"
          dynamodb:
            keys:
              pk: "sensor#temp-001"
            newImage:
              pk: "sensor#temp-001"
              reading: 72.5
              unit: "fahrenheit"
            sequenceNumber: "98765"
    output_batches:
      - - json_contains:
            event_type: "INSERT"
            table: "sensor_data"
            sequence_number: "98765"
            keys:
              pk: "sensor#temp-001"
            new_image:
              reading: 72.5
              unit: "fahrenheit"
# end::tests[]
