= archive
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Parsing","Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Archives all the messages of a batch into a single message according to the selected archive format.

```yml
# Config fields, showing default values
label: ""
archive:
  format: "" # No default (required)
  path: ""
```

Some archive formats (such as tar, zip) treat each archive item (message part) as a file with a path. Since message parts only contain raw data a unique path must be generated for each part. This can be done by using function interpolations on the 'path' field as described in xref:configuration:interpolation.adoc#bloblang-queries[Bloblang queries]. For types that aren't file based (such as binary) the file field is ignored.

The resulting archived message adopts the metadata of the _first_ message part of the batch.

The functionality of this processor depends on being applied across messages that are batched. You can find out more about batching xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/processors/archive.adoc[]

include::redpanda-connect:components:partial$examples/processors/archive.adoc[]

// end::single-source[]