= avro
// tag::single-source[]
:type: processor
:status: beta
:categories: ["Parsing"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Performs Avro based operations on messages based on a schema.

```yml
# Config fields, showing default values
label: ""
avro:
  operator: "" # No default (required)
  encoding: textual
  schema: ""
  schema_path: ""
```

WARNING: If you are consuming or generating messages using a schema registry service then it is likely this processor will fail as those services require messages to be prefixed with the identifier of the schema version being used. Instead, try the xref:components:processors/schema_registry_encode.adoc[`schema_registry_encode`] and xref:components:processors/schema_registry_decode.adoc[`schema_registry_decode`] processors.

== Operators

=== `to_json`

Converts Avro documents into a JSON structure. This makes it easier to
manipulate the contents of the document within Benthos. The encoding field
specifies how the source documents are encoded.

=== `from_json`

Attempts to convert JSON documents into Avro documents according to the
specified encoding.

include::redpanda-connect:components:partial$fields/processors/avro.adoc[]

// end::single-source[]