= branch
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Composition"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


The `branch` processor allows you to create a new request message via a xref:guides:bloblang/about.adoc[Bloblang mapping], execute a list of processors on the request messages, and, finally, map the result back into the source message using another mapping.

```yml
# Config fields, showing default values
label: ""
branch:
  request_map: ""
  processors: [] # No default (required)
  result_map: ""
```

This is useful for preserving the original message contents when using processors that would otherwise replace the entire contents.

== Metadata

Metadata fields that are added to messages during branch processing will not be automatically copied into the resulting message. In order to do this you should explicitly declare in your `result_map` either a wholesale copy with `meta = metadata()`, or selective copies with `meta foo = metadata("bar")` and so on. It is also possible to reference the metadata of the origin message in the `result_map` using the xref:guides:bloblang/about.adoc#metadata[`@` operator].

== Error handling

If the `request_map` fails the child processors will not be executed. If the child processors themselves result in an (uncaught) error then the `result_map` will not be executed. If the `result_map` fails the message will remain unchanged. Under any of these conditions standard xref:configuration:error_handling.adoc[error handling methods] can be used in order to filter, DLQ or recover the failed messages.

== Conditional branching

If the root of your request map is set to `deleted()` then the branch processors are skipped for the given message, this allows you to conditionally branch messages.

include::redpanda-connect:components:partial$fields/processors/branch.adoc[]

include::redpanda-connect:components:partial$examples/processors/branch.adoc[]

// end::single-source[]