= cache
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Integration"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Performs operations against a xref:components:caches/about.adoc[cache resource] for each message, allowing you to store or retrieve data within message payloads.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/cache.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/cache.yaml[]
```

--
======

For use cases where you wish to cache the result of processors, consider using the xref:components:processors/cached.adoc[`cached` processor] instead.

This processor will interpolate functions within the `key` and `value` fields individually for each message. This allows you to specify dynamic keys and values based on the contents of the message payloads and metadata. You can find a list of functions in xref:configuration:interpolation.adoc#bloblang-queries[Bloblang queries].

include::redpanda-connect:components:partial$examples/processors/cache.adoc[]

include::redpanda-connect:components:partial$fields/processors/cache.adoc[]

== Operators

=== `set`

Set a key in the cache to a value. If the key already exists the contents are
overridden.

=== `add`

Set a key in the cache to a value. If the key already exists the action fails
with a 'key already exists' error, which can be detected with
xref:configuration:error_handling.adoc[processor error handling].

=== `get`

Retrieve the contents of a cached key and replace the original message payload
with the result. If the key does not exist the action fails with an error, which
can be detected with xref:configuration:error_handling.adoc[processor error handling].

=== `exists`

Check whether a specific key is in the cache and replace the original message payload with `true` if the key exists, or `false` if it doesn’t.

=== `delete`

Delete a key and its contents from the cache. If the key does not exist the
action is a no-op and will not fail with an error.

// end::single-source[]