= cached
// tag::single-source[]
:type: processor
:status: experimental
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Cache the result of applying one or more processors to messages identified by a key. If the key already exists within the cache the contents of the message will be replaced with the cached result instead of applying the processors. This component is therefore useful in situations where an expensive set of processors need only be executed periodically.

ifndef::env-cloud[]
Introduced in version 4.3.0.
endif::[]

```yml
# Config fields, showing default values
label: ""
cached:
  cache: "" # No default (required)
  skip_on: errored() # No default (optional)
  key: my_foo_result # No default (required)
  ttl: "" # No default (optional)
  processors: [] # No default (required)
```

The format of the data when stored within the cache is a custom and versioned schema chosen to balance performance and storage space. It is therefore not possible to point this processor to a cache that is pre-populated with data that this processor has not created itself.

include::redpanda-connect:components:partial$examples/processors/cached.adoc[]

include::redpanda-connect:components:partial$fields/processors/cached.adoc[]

// end::single-source[]