= cohere_chat
// tag::single-source[]
:type: processor
:categories: ["AI"]

component_type_dropdown::[]


Generates responses to messages in a chat conversation, using the https://docs.cohere.com/docs/chat-api[Cohere API^] and external tools.

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/cohere_chat.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/cohere_chat.yaml[]
```

--
======

This processor sends the contents of user prompts to the Cohere API, which generates responses using all available context, including supplementary data provided by external tools. By default, the processor submits the entire payload of each message as a string, unless you use the `prompt` field to customize it.

To learn more about chat completion, see the https://docs.cohere.com/docs/chat-api[Cohere API documentation^].

include::redpanda-connect:components:partial$fields/processors/cohere_chat.adoc[]

== Example

In this pipeline configuration, the Command R+ model executes a number of processors, which make a tool call to retrieve weather data for a specific city.

```yaml
input:
  generate:
    count: 1
    mapping: |
      root = "What is the weather like in Chicago?"
pipeline:
  processors:
    - cohere_chat:
        auth_token: my_cohere_api_token
        model: command-r-plus
        prompt: "${!content().string()}"
        tools:
          - name: GetWeather
            description: "Retrieve the weather for a specific city"
            parameters:
              required: ["city"]
              properties:
                city:
                  type: string
                  description: the city to look up the weather for
            processors:
              - http:
                  verb: GET
                  url: 'https://wttr.in/${!this.city}?T'
                  headers:
                    User-Agent: curl/8.11.1 # Returns a text string from the weather website
output:
  stdout: {}
```

// end::single-source[]