= cohere_chat
// tag::single-source[]
:type: processor
:page-beta: true
:categories: ["AI"]

component_type_dropdown::[]


Generates responses to messages in a chat conversation, using the https://docs.cohere.com/docs/chat-api[Cohere API^] and external tools.

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--
```yml
# Common configuration fields, showing default values
label: ""
cohere_chat:
  base_url: https://api.cohere.com
  auth_token: "" # No default (required)
  model: command-r-plus # No default (required)
  prompt: "" # No default (optional)
  system_prompt: "" # No default (optional)
  max_tokens: 0 # No default (optional)
  temperature: 0 # No default (optional)
  response_format: text
  json_schema: "" # No default (optional)
  max_tool_calls: 10
  tools: []
```
--
Advanced::
+
--
```yml
# All configuration fields, showing default values
label: ""
cohere_chat:
  base_url: https://api.cohere.com
  auth_token: "" # No default (required)
  model: command-r-plus # No default (required)
  prompt: "" # No default (optional)
  system_prompt: "" # No default (optional)
  max_tokens: 0 # No default (optional)
  temperature: 0 # No default (optional)
  response_format: text
  json_schema: "" # No default (optional)
  schema_registry:
    url: "" # No default (required)
    subject: "" # No default (required)
    refresh_interval: "" # No default (optional)
    tls:
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    oauth:
      enabled: false
      consumer_key: ""
      consumer_secret: ""
      access_token: ""
      access_token_secret: ""
    basic_auth:
      enabled: false
      username: ""
      password: ""
    jwt:
      enabled: false
      private_key_file: ""
      signing_method: ""
      claims: {}
      headers: {}
  top_p: 0 # No default (optional)
  frequency_penalty: 0 # No default (optional)
  presence_penalty: 0 # No default (optional)
  seed: 0 # No default (optional)
  stop: [] # No default (optional)
  max_tool_calls: 10
  tools: []
```
--
======

This processor sends the contents of user prompts to the Cohere API, which generates responses using all available context, including supplementary data provided by external tools. By default, the processor submits the entire payload of each message as a string, unless you use the `prompt` field to customize it.

To learn more about chat completion, see the https://docs.cohere.com/docs/chat-api[Cohere API documentation^].

include::redpanda-connect:components:partial$fields/processors/cohere_chat.adoc[]

== Example

In this pipeline configuration, the Command R+ model executes a number of processors, which make a tool call to retrieve weather data for a specific city.

```yaml
input:
  generate:
    count: 1
    mapping: |
      root = "What is the weather like in Chicago?"
pipeline:
  processors:
    - cohere_chat:
        auth_token: my_cohere_api_token
        model: command-r-plus
        prompt: "${!content().string()}"
        tools:
          - name: GetWeather
            description: "Retrieve the weather for a specific city"
            parameters:
              required: ["city"]
              properties:
                city:
                  type: string
                  description: the city to look up the weather for
            processors:
              - http:
                  verb: GET
                  url: 'https://wttr.in/${!this.city}?T'
                  headers:
                    User-Agent: curl/8.11.1 # Returns a text string from the weather website
output:
  stdout: {}
```

// end::single-source[]