= command
:type: processor
:status: experimental
:categories: ["Integration"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Executes a command for each message.

Introduced in version 4.21.0.

```yml
# Config fields, showing default values
label: ""
command:
  name: bash # No default (required)
  args_mapping: '[ "-c", this.script_path ]' # No default (optional)
```

The specified command is executed for each message processed, with the raw bytes of the message being fed into the stdin of the command process, and the resulting message having its contents replaced with the stdout of it.

== Performance

Since this processor executes a new process for each message performance will likely be an issue for high throughput streams. If this is the case then consider using the xref:components:processors/subprocess.adoc[`subprocess` processor] instead as it keeps the underlying process alive long term and uses codecs to insert and extract inputs and outputs to it via stdin/stdout.

== Error handling

If a non-zero error code is returned by the command then an error containing the entirety of stderr (or a generic message if nothing is written) is set on the message. These failed messages will continue through the pipeline unchanged, but can be dropped or placed in a dead letter queue according to your config, you can read about xref:configuration:error_handling.adoc[these patterns].

If the command is successful but stderr is written to then a metadata field `command_stderr` is populated with its contents.

include::redpanda-connect:components:partial$fields/processors/command.adoc[]

include::redpanda-connect:components:partial$examples/processors/command.adoc[]

