= google_drive_download
// tag::single-source[]
:type: processor
:categories: ["AI"]

component_type_dropdown::[]

Downloads files from Google Drive that contain matching file IDs.

Try out the <<example,example pipeline on this page>>, which downloads all files from your Google Drive.

ifndef::env-cloud[]
Introduced in version 4.53.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/google_drive_download.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/google_drive_download.yaml[]
```

--
======

== Authentication

By default, this processor uses https://cloud.google.com/docs/authentication/application-default-credentials[Google Application Default Credentials (ADC)^] to authenticate with Google APIs.

To set up local ADC authentication, use the following `gcloud` commands:

- Authenticate using Application Default Credentials and grant read-only access to your Google Drive.
+
```bash
gcloud auth application-default login --scopes='openid,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/drive.readonly'
```
- Assign a quota project to the Application Default Credentials when using a user account.
+
```bash
gcloud auth application-default set-quota-project <project-id>
```
+
Replace the `<project-id>` placeholder with your Google Cloud project ID

To use a service account instead, create a JSON key for the account and add it to the <<credentials_json,`credentials_json`>> field. To access Google Drive files using a service account, either:

- Explicitly share files with the service account's email account
- Use https://support.google.com/a/answer/162106[domain-wide delegation^] to share all files within a Google Workspace

include::redpanda-connect:components:partial$fields/processors/google_drive_download.adoc[]

== Example

This example downloads all files from a Google Drive.

```yaml
input:
  stdin: {}
pipeline:
  processors:
    - google_drive_search:
        query: "${!content().string()}"
    - mutation: 'meta path = this.name'
    - google_drive_download:
        file_id: "${!this.id}"
        mime_type: "${!this.mimeType}"
output:
  file:
    path: "${!@path}"
    codec: all-bytes
```


// end::single-source[]