= grok
:type: processor
:commercial-names: Grok
:status: stable
:categories: ["Parsing"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Parses messages into a structured format by attempting to apply a list of Grok expressions, the first expression to result in at least one value replaces the original message with a JSON object containing the values.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/grok.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/grok.yaml[]
```

--
======

Type hints within patterns are respected, therefore with the pattern `%\{WORD:first},%{INT:second:int}` and a payload of `foo,1` the resulting payload would be `\{"first":"foo","second":1}`.

== Performance

This processor currently uses the https://golang.org/s/re2syntax[Go RE2^] regular expression engine, which is guaranteed to run in time linear to the size of the input. However, this property often makes it less performant than PCRE based implementations of grok. For more information, see https://swtch.com/~rsc/regexp/regexp1.html.

include::redpanda-connect:components:partial$examples/processors/grok.adoc[]

include::redpanda-connect:components:partial$fields/processors/grok.adoc[]

== Default patterns

For summary of the default patterns on offer, see https://github.com/Jeffail/grok/blob/master/patterns.go#L5.

