= http
// tag::single-source[]
:type: processor
:commercial-names: HTTP
:status: stable
:categories: ["Integration"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Performs a HTTP request using a message batch as the request body, and replaces the original message parts with the body of the response.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/http.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/http.yaml[]
```

--
======

== Rate limit requests

You can use the `rate_limit` field to specify a xref:components:rate_limits/about.adoc[rate limit resource], which restricts the number of requests processed service-wide, regardless of how many components you run in parallel.

== Dynamic URL and header settings

You can set the <<url,`url`>> and <<headers,`headers`>> values dynamically using xref:configuration:interpolation.adoc#bloblang-queries[function interpolations].

== Map payloads with the branch processor

You can use the xref:components:processors/branch.adoc[`branch` processor] to transform or encode the payload into a specific request body format, and map the response back into the original payload instead of replacing it entirely.

This example uses a xref:components:processors/branch.adoc[`branch` processor] to strip the request message into an empty body (`request_map: 'root = ""'`), grab an HTTP payload, and place the result back into the original message at the path `repo.status`:

```yaml
pipeline:
  processors:
    - branch:
        request_map: 'root = ""'
        processors:
          - http:
              url: https://hub.docker.com/v2/repositories/jeffail/benthos
              verb: GET
              headers:
                Content-Type: application/json
        result_map: 'root.repo.status = this'
```

== Response codes

HTTP response codes in the 200-299 range indicate a successful response. You can use the <<successful_on,`successful_on`>> field to add more success status codes.

HTTP status codes in the 300-399 range are redirects. The <<follow_redirects,`follow_redirects` field>> determines how these responses are handled.

If a request returns a response code that matches an entry in:

- The <<backoff_on,`backoff_on` field>>, the request is retried after increasing intervals.

- The <<drop_on,`drop_on` field>>, the request is immediately treated as a failure.

== Add metadata to errors

If a request returns an error response code, this processor sets a  `http_status_code` metadata field in the resulting message.

TIP: You can use the <<extract_headers, `extract_headers`>> field to define rules for copying headers into messages generated from the response.

== Error handling

When all retry attempts for a message are exhausted, this processor cancels the attempt. By default, the failed message continues through the pipeline unchanged unless you configure other error-handling. For example, you might want to drop failed messages or route them to a dead letter queue. For more information, see xref:configuration:error_handling.adoc[Error Handling].

include::redpanda-connect:components:partial$fields/processors/http.adoc[]

// end::single-source[]