= jq
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Mapping"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Transforms and filters messages using jq queries.


[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
label: ""
jq:
  query: "" # No default (required)
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
label: ""
jq:
  query: "" # No default (required)
  raw: false
  output_raw: false
```

--
======

[TIP]
.Try out Bloblang
====
For better performance and improved capabilities try out native Redpanda Connect mapping with the xref:components:processors/mapping.adoc[`mapping` processor].
====

The provided query is executed on each message, targeting either the contents as a structured JSON value or as a raw string using the field `raw`, and the message is replaced with the query result.

Message metadata is also accessible within the query from the variable `$metadata`.

This processor uses the https://github.com/itchyny/gojq[gojq library^], and therefore does not require jq to be installed as a dependency. However, this also means there are some https://github.com/itchyny/gojq#difference-to-jq[differences in how these queries are executed^] versus the jq cli.

If the query does not emit any value then the message is filtered, if the query returns multiple values then the resulting message will be an array containing all values.

The full query syntax is described in https://stedolan.github.io/jq/manual/[jq's documentation^].

== Error handling

Queries can fail, in which case the message remains unchanged, errors are logged, and the message is flagged as having failed, allowing you to use xref:configuration:error_handling.adoc[standard processor error handling patterns].

include::redpanda-connect:components:partial$fields/processors/jq.adoc[]

include::redpanda-connect:components:partial$examples/processors/jq.adoc[]

// end::single-source[]