= metric
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Emit custom metrics by extracting values from messages.

```yml
# Config fields, showing default values
label: ""
metric:
  type: "" # No default (required)
  name: "" # No default (required)
  labels: {} # No default (optional)
  value: ""
```

This processor works by evaluating an xref:configuration:interpolation.adoc#bloblang-queries[interpolated field `value`] for each message and updating a emitted metric according to the <<types, type>>.

Custom metrics such as these are emitted along with Redpanda Connect internal metrics, where you can customize where metrics are sent, which metric names are emitted and rename them as/when appropriate. For more information see the xref:components:metrics/about.adoc[metrics docs].

include::redpanda-connect:components:partial$fields/processors/metric.adoc[]

include::redpanda-connect:components:partial$examples/processors/metric.adoc[]

== Types

=== `counter`

Increments a counter by exactly 1, the contents of `value` are ignored
by this type.

=== `counter_by`

If the contents of `value` can be parsed as a positive integer value
then the counter is incremented by this value.

For example, the following configuration will increment the value of the
`count.custom.field` metric by the contents of `field.some.value`:

```yaml
pipeline:
  processors:
    - metric:
        type: counter_by
        name: CountCustomField
        value: ${!json("field.some.value")}
```

=== `gauge`

If the contents of `value` can be parsed as a positive integer value
then the gauge is set to this value.

For example, the following configuration will set the value of the
`gauge.custom.field` metric to the contents of `field.some.value`:

```yaml
pipeline:
  processors:
    - metric:
        type: gauge
        name: GaugeCustomField
        value: ${!json("field.some.value")}
```

=== `timing`

Equivalent to `gauge` where instead the metric is a timing. It is recommended that timing values are recorded in nanoseconds in order to be consistent with standard Redpanda Connect timing metrics, as in some cases these values are automatically converted into other units such as when exporting timings as histograms with Prometheus metrics.

// end::single-source[]