= openai_chat_completion
// tag::single-source[]
:type: processor
:categories: ["AI"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Generates responses to messages in a chat conversation, using the OpenAI API and external tools.

ifndef::env-cloud[]
Introduced in version 4.32.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
openai_chat_completion:
  server_address: https://api.openai.com/v1
  api_key: "" # No default (required)
  model: gpt-4o # No default (required)
  prompt: "" # No default (optional)
  system_prompt: "" # No default (optional)
  history: "" # No default (optional)
  image: 'root = this.image.decode("base64") # decode base64 encoded image' # No default (optional)
  max_tokens: 0 # No default (optional)
  temperature: 0 # No default (optional)
  user: "" # No default (optional)
  response_format: text
  json_schema:
    name: "" # No default (required)
    schema: "" # No default (required)
  tools: [] # No default (required)
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
openai_chat_completion:
  server_address: https://api.openai.com/v1
  api_key: "" # No default (required)
  model: gpt-4o # No default (required)
  prompt: "" # No default (optional)
  system_prompt: "" # No default (optional)
  history: "" # No default (optional)
  image: 'root = this.image.decode("base64") # decode base64 encoded image' # No default (optional)
  max_tokens: 0 # No default (optional)
  temperature: 0 # No default (optional)
  user: "" # No default (optional)
  response_format: text
  json_schema:
    name: "" # No default (required)
    description: "" # No default (optional)
    schema: "" # No default (required)
  schema_registry:
    url: "" # No default (required)
    name_prefix: schema_registry_id_
    subject: "" # No default (required)
    refresh_interval: "" # No default (optional)
    tls:
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: "" # No default (optional)
      root_cas_file: "" # No default (optional)
      client_certs: [] # Optional
    oauth:
      enabled: false
      consumer_key: "" # No default (optional)
      consumer_secret: "" # No default (optional)
      access_token: "" # No default (optional)
      access_token_secret: "" # No default (optional)
    basic_auth:
      enabled: false
      username: "" # No default (optional)
      password: "" # No default (optional)
    jwt:
      enabled: false
      private_key_file: "" # No default (optional)
      signing_method: "" # No default (optional)
      claims: {} # Optional
      headers: {} # Optional
  top_p: 0 # No default (optional)
  frequency_penalty: 0 # No default (optional)
  presence_penalty: 0 # No default (optional)
  seed: 0 # No default (optional)
  stop: [] # No default (optional)
  tools: [] # No default (required)
```

--
======

This processor sends user prompts to the OpenAI API, and the specified large language model (LLM) generates responses using all available context, including supplementary data provided by <<tools, external tools>>. By default, the processor submits the entire payload of each message as a string, unless you use the `prompt` configuration field to customize it.

To learn more about chat completion, see the https://platform.openai.com/docs/guides/chat-completions[OpenAI API documentation^], and <<Examples, Examples>>.

include::redpanda-connect:components:partial$fields/processors/openai_chat_completion.adoc[]

nclude::redpanda-connect:components:partial$examples/processors/openai_chat_completion.adoc[]

// end::single-source[]