= openai_chat_completion
// tag::single-source[]
:type: processor
:categories: ["AI"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Generates responses to messages in a chat conversation, using the OpenAI API and external tools.

ifndef::env-cloud[]
Introduced in version 4.32.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/openai_chat_completion.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/openai_chat_completion.yaml[]
```

--
======

This processor sends user prompts to the OpenAI API, and the specified large language model (LLM) generates responses using all available context, including supplementary data provided by <<tools, external tools>>. By default, the processor submits the entire payload of each message as a string, unless you use the `prompt` configuration field to customize it.

To learn more about chat completion, see the https://platform.openai.com/docs/guides/chat-completions[OpenAI API documentation^], and <<Examples, Examples>>.

include::redpanda-connect:components:partial$fields/processors/openai_chat_completion.adoc[]

nclude::redpanda-connect:components:partial$examples/processors/openai_chat_completion.adoc[]

// end::single-source[]