= parse_log
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Parsing"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]

ifndef::env-cloud[]
Parses common log <<formats>> into <<codecs, structured data>>. This is easier and often much faster than xref:components:processors/grok.adoc[`grok`].
endif::[]
ifdef::env-cloud[]
Parses common log <<formats>> into <<codecs, structured data>>.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common config fields, showing default values
label: ""
parse_log:
  format: "" # No default (required)
```

--
Advanced::
+
--

```yml
# All config fields, showing default values
label: ""
parse_log:
  format: "" # No default (required)
  best_effort: true
  allow_rfc3339: true
  default_year: current
  default_timezone: UTC
```

--
======

include::redpanda-connect:components:partial$fields/processors/parse_log.adoc[]

== Codecs

Currently the only supported structured data codec is `json`.

== Formats

=== `syslog_rfc5424`

Attempts to parse a log following the https://tools.ietf.org/html/rfc5424[Syslog RFC5424^] spec. The resulting structured document may contain any of the following fields:

- `message` (string)
- `timestamp` (string, RFC3339)
- `facility` (int)
- `severity` (int)
- `priority` (int)
- `version` (int)
- `hostname` (string)
- `procid` (string)
- `appname` (string)
- `msgid` (string)
- `structureddata` (object)

=== `syslog_rfc3164`

Attempts to parse a log following the https://tools.ietf.org/html/rfc3164[Syslog rfc3164] spec. The resulting structured document may contain any of the following fields:

- `message` (string)
- `timestamp` (string, RFC3339)
- `facility` (int)
- `severity` (int)
- `priority` (int)
- `hostname` (string)
- `procid` (string)
- `appname` (string)
- `msgid` (string)

// end::single-source[]