= protobuf
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Parsing"]


component_type_dropdown::[]

Handles conversions between JSON documents and protobuf messages using reflection, which allows you to make conversions from or to the target `.proto` files.

For more information about JSON mapping of protobuf messages, see https://protobuf.dev/programming-guides/json/[ProtoJSON Format^] and <<Examples, Examples>>.


```yml
# Configuration fields, showing default values
label: ""
protobuf:
  operator: "" # No default (required)
  message: "" # No default (required)
  discard_unknown: false
  use_proto_names: false
  import_paths: []
  use_enum_numbers: false
```

== Performance considerations

Processing protobuf messages using reflection is less performant than using generated native code. For scenarios where performance is critical, consider using https://github.com/benthosdev/benthos-plugin-example[Redpanda Connect plugins^].

== Operators

=== `to_json`

Converts protobuf messages into a generic JSON structure, which makes it easier to manipulate the contents of the JSON document within Redpanda Connect.

=== `from_json`

Attempts to create a target protobuf message from a generic JSON structure.

include::redpanda-connect:components:partial$fields/processors/protobuf.adoc[]

nclude::redpanda-connect:components:partial$examples/processors/protobuf.adoc[]

// end::single-source[]