= qdrant
// tag::single-source[]
:type: processor
:categories: ["AI"]

component_type_dropdown::[]
Query items within a https://qdrant.tech/documentation/concepts/collections/[Qdrant collection^] and filter the returned results.

ifndef::env-cloud[]
Introduced in version 4.54.0.
endif::[]

[tabs]
======
Common::
+
--
```yml
# Common configuration fields, showing default values
label: ""
qdrant:
  grpc_host: localhost:6334 # No default (required)
  api_token: ""
  collection_name: "" # No default (required)
  vector_mapping: root = [1.2, 0.5, 0.76] # No default (required)
  filter: | # No default (optional)
    root.must = [
    	{"has_id":{"has_id":[{"num": 8}, { "uuid":"1234-5678-90ab-cdef" }]}},
    	{"field":{"key": "city", "match": {"text": "London"}}},
    ]
  payload_fields: []  
  payload_filter: include
  limit: 10
```
--
Advanced::
+
--
```yml
# All configuration fields, showing default values
label: ""
qdrant:
  grpc_host: localhost:6334 # No default (required)
  api_token: ""
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  collection_name: "" # No default (required)
  vector_mapping: root = [1.2, 0.5, 0.76] # No default (required)
  filter: | # No default (optional)
    root.must = [
    	{"has_id":{"has_id":[{"num": 8}, { "uuid":"1234-5678-90ab-cdef" }]}},
    	{"field":{"key": "city", "match": {"text": "London"}}},
    ]
  payload_fields: []
  payload_filter: include
  limit: 10
```
--
======

== Fields

=== `grpc_host`

The gRPC host of the Qdrant server.

*Type*: `string`

*Default*: `""`

```yml
# Examples

grpc_host: localhost:6334

grpc_host: xyz-example.eu-central.aws.cloud.qdrant.io:6334
```

=== `api_token`

The Qdrant API token to use for authentication, which defaults to an empty string.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

=== `tls`

Specify a secure TLS (HTTPS) connection to the Qdrant server.

*Type*: `object`

=== `tls.enabled`

Whether custom TLS settings are enabled.

*Type*: `bool`

*Default*: `false`

=== `tls.skip_cert_verify`

Whether to skip server-side certificate verification.

*Type*: `bool`

*Default*: `false`

=== `tls.enable_renegotiation`

Whether to allow the remote server to request renegotiation. Enable this option if you're seeing the error message `local error: tls: no renegotiation`.

*Type*: `bool`

*Default*: `false`

ifndef::env-cloud[]
Requires version 3.45.0 or newer
endif::[]

=== `tls.root_cas`

Specify a certificate authority to use (optional). This is a string that represents a certificate chain from the parent-trusted root certificate, through possible intermediate signing certificates, to the host certificate.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Examples

root_cas: |-
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
```

=== `tls.root_cas_file`

Specify the path to a root certificate authority file (optional). This is a file, often with a `.pem` extension, which contains a certificate chain from the parent-trusted root certificate, through possible intermediate signing certificates, to the host certificate.

*Type*: `string`

*Default*: `""`

```yml
# Examples

root_cas_file: ./root_cas.pem
```

=== `tls.client_certs`

A list of client certificates to use. For each certificate specify values for either the `cert` and `key` fields, or `cert_file` and `key_file` fields.

*Type*: `array`

*Default*: `[]`

```yml
# Examples

client_certs:
  - cert: foo
    key: bar

client_certs:
  - cert_file: ./example.pem
    key_file: ./example.key
```

=== `tls.client_certs[].cert`

The plain text certificate to use.

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key`

The plain text certificate key to use.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].cert_file`

The path to the certificate to use.

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key_file`

The path of a certificate key to use.

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].password`

The plain text password for when the private key is password encrypted in PKCS#1 or PKCS#8 format. The obsolete `pbeWithMD5AndDES-CBC` algorithm is not supported for the PKCS#8 format. 

WARNING: The `pbeWithMD5AndDES-CBC` algorithm does not authenticate ciphertext, and is vulnerable to padding oracle attacks that may allow an attacker to recover the plain text password.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Examples

password: foo

password: ${KEY_PASSWORD}
```

=== `collection_name`

The name of the Qdrant collection you want to query. This field supports xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions].

*Type*: `string`

=== `vector_mapping`

A mapping to extract search vectors from the returned document.

*Type*: `string`


```yml
# Examples

vector_mapping: root = [1.2, 0.5, 0.76]

vector_mapping: root = this.vector

vector_mapping: root = [[0.352,0.532,0.532,0.234],[0.352,0.532,0.532,0.234]]

vector_mapping: 'root = {"some_sparse": {"indices":[23,325,532],"values":[0.352,0.532,0.532]}}'

vector_mapping: 'root = {"some_multi": [[0.352,0.532,0.532,0.234],[0.352,0.532,0.532,0.234]]}'

vector_mapping: 'root = {"some_dense": [0.352,0.532,0.532,0.234]}'
```

=== `filter`

Specify additional filtering to perform on returned results. Mappings must return https://qdrant.tech/documentation/concepts/filtering/[a valid filter^] using the proto3-encoded form.

*Type*: `string`

```yml
# Examples

filter: |2
  root.must = [
  	{"has_id":{"has_id":[{"num": 8}, { "uuid":"1234-5678-90ab-cdef" }]}},
  	{"field":{"key": "city", "match": {"text": "London"}}},
  ]

filter: |2
  root.must = [
  	{"field":{"key": "city", "match": {"text": "London"}}},
  ]
  root.must_not = [
  	{"field":{"color": "city", "match": {"text": "red"}}},
  ]
```

=== `payload_fields`

The fields to include or exclude in returned results. Use this field in combination with `payload_filter`.

*Type*: `array`

*Default*: `[]`

=== `payload_filter`

Whether to include or exclude the fields specified in `payload_fields` from the returned results.

*Type*: `string`

*Default*: `include`

|===
| Option | Description

| `exclude`
| Exclude `payload_fields` from the returned results.

| `include`
| Include `payload_fields` from the returned results.

|===

=== `limit`

The maximum number of points to return from the collection.

*Type*: `int`

*Default*: `10`



// end::single-source[]