= retry
// tag::single-source[]
:type: processor
:status: beta
:categories: ["Composition"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Attempts to execute a series of child processors until success.

ifndef::env-cloud[]
Introduced in version 4.27.0.
endif::[]

```yml
# Config fields, showing default values
label: ""
retry:
  backoff:
    initial_interval: 500ms
    max_interval: 10s
    max_elapsed_time: 1m
  processors: [] # No default (required)
  parallel: false
  max_retries: 0
```

Executes child processors and if a resulting message is errored then, after a specified backoff period, the same original message will be attempted again through those same processors. If the child processors result in more than one message then the retry mechanism will kick in if _any_ of the resulting messages are errored.

It is important to note that any mutations performed on the message during these child processors will be discarded for the next retry, and therefore it is safe to assume that each execution of the child processors will always be performed on the data as it was when it first reached the retry processor.

By default the retry backoff has a specified <<backoffmax_elapsed_time,`max_elapsed_time`>>, if this time period is reached during retries and an error still occurs these errored messages will proceed through to the next processor after the retry (or your outputs). Normal xref:configuration:error_handling.adoc[error handling patterns] can be used on these messages.

In order to avoid permanent loops any error associated with messages as they first enter a retry processor will be cleared.

== Metadata

This processor adds the following metadata fields to each message:

```text
- retry_count - The number of retry attempts.
- backoff_duration - The total time elapsed while performing retries.
```

[CAUTION]
.Batching
====
If you wish to wrap a batch-aware series of processors then take a look at the <<batching, batching section>>.
====

include::redpanda-connect:components:partial$examples/processors/retry.adoc[]

include::redpanda-connect:components:partial$fields/processors/retry.adoc[]

== Batching

When messages are batched the child processors of a retry are executed for each individual message in isolation, performed serially by default but in parallel when the field <<parallel, `parallel`>> is set to `true`. This is an intentional limitation of the retry processor and is done in order to ensure that errors are correctly associated with a given input message. Otherwise, the archiving, expansion, grouping, filtering and so on of the child processors could obfuscate this relationship.

If the target behavior of your retried processors is "batch aware", in that you wish to perform some processing across the entire batch of messages and repeat it in the event of errors, you can use an xref:components:processors/archive.adoc[`archive` processor] to collapse the batch into an individual message. Then, within these child processors either perform your batch aware processing on the archive, or use an xref:components:processors/unarchive.adoc[`unarchive` processor] in order to expand the single message back out into a batch.

For example, if the retry processor were being used to wrap an HTTP request where the payload data is a batch archived into a JSON array it should look something like this:

```yaml
pipeline:
  processors:
    - archive:
        format: json_array
    - retry:
        processors:
          - http:
              url: example.com/nope
              verb: POST
    - unarchive:
        format: json_array
```

// end::single-source[]