= schema_registry_encode
// tag::single-source[]
:type: processor
:status: beta
:categories: ["Parsing","Integration"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Automatically encodes and validates messages with schemas from a Confluent Schema Registry service. 

This processor uses the https://github.com/twmb/franz-go/tree/master/pkg/sr[Franz Kafka Schema Registry client^].

ifndef::env-cloud[]
Introduced in version 3.58.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
schema_registry_encode:
  url: "" # No default (required)
  subject: foo # No default (required)
  refresh_period: 10m
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
schema_registry_encode:
  url: "" # No default (required)
  subject: foo # No default (required)
  refresh_period: 10m
  avro_raw_json: false
  oauth:
    enabled: false
    consumer_key: ""
    consumer_secret: ""
    access_token: ""
    access_token_secret: ""
  basic_auth:
    enabled: false
    username: ""
    password: ""
  jwt:
    enabled: false
    private_key_file: ""
    signing_method: ""
    claims: {}
    headers: {}
  tls:
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
```

--
======

Encodes messages automatically from schemas obtains from a https://docs.confluent.io/platform/current/schema-registry/index.html[Confluent Schema Registry service^] by polling the service for the latest schema version for target subjects.

If a message fails to encode under the schema then it will remain unchanged and the error can be caught using xref:configuration:error_handling.adoc[error-handling methods].

Avro, Protobuf and JSON schemas are supported, all are capable of expanding from schema references as of v4.22.0.

== Avro JSON format

By default, this processor expects documents formatted as https://avro.apache.org/docs/current/specification/[Avro JSON^] when encoding with Avro schemas. In this format, the value of a union is encoded in JSON as follows:

- If the union's type is `null`, it is encoded as a JSON `null`.
- Otherwise, the union is encoded as a JSON object with one name/value pair. The name is the type's name, and the value is the recursively-encoded value. The user-specified name is used for Avro's named types (record, fixed, or enum). For other types, the type name is used.

For example, the union schema `["null","string","Transaction"]`, where `Transaction` is a record name, would encode:

- A `null` as a JSON `null`
- The string `"a"` as `{"string": "a"}`
- A `Transaction` instance as `{"Transaction": {...}}`, where `{...}` indicates the JSON encoding of a `Transaction` instance

Alternatively, you can consume documents in https://pkg.go.dev/github.com/linkedin/goavro/v2#NewCodecForStandardJSONFull[standard/raw JSON format^] by setting the field <<avro_raw_json,`avro_raw_json`>> to `true`.

=== Known issues

Important! There is an outstanding issue in the https://github.com/linkedin/goavro[avro serializing library^] that Redpanda Connect uses which means it https://github.com/linkedin/goavro/issues/252[doesn't encode logical types correctly^]. It's still possible to encode logical types that are in-line with the spec if `avro_raw_json` is set to true, though now of course non-logical types will not be in-line with the spec.

== Protobuf format

This processor encodes Protobuf messages either from any format parsed within Redpanda Connect (encoded as JSON by default), or from raw JSON documents. For more information about the JSON mapping of Protobuf messages, see the https://developers.google.com/protocol-buffers/docs/proto3#json[Protocol Buffers documentation^].

=== Multiple message support

When a target subject presents a Protobuf schema that contains multiple messages it becomes ambiguous which message definition a given input data should be encoded against. In such scenarios Redpanda Connect will attempt to encode the data against each of them and select the first to successfully match against the data, this process currently *ignores all nested message definitions*. In order to speed up this exhaustive search the last known successful message will be attempted first for each subsequent input.

We will be considering alternative approaches in future so please https://redpanda.com/slack[get in touch^] with thoughts and feedback.

include::redpanda-connect:components:partial$fields/processors/schema_registry_encode.adoc[]

// end::single-source[]