= schema_registry_decode
// tag::single-source[]
:type: processor
:status: beta
:page-beta: true
:categories: ["Parsing","Integration"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Automatically decodes and validates messages with schemas from a Confluent Schema Registry service.

This processor uses the https://github.com/twmb/franz-go/tree/master/pkg/sr[Franz Kafka Schema Registry client^].


[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
schema_registry_decode:
  avro:
    raw_unions: false # No default (optional)
    preserve_logical_types: false
  cache_duration: 10m
  url: "" # No default (required)
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
schema_registry_decode:
  avro:
    raw_unions: false
    preserve_logical_types: false
    mapping: "" # No default (optional)
  cache_duration: 10m
  url: "" # No default (required)
  oauth:
    enabled: false
    consumer_key: "" # Optional
    consumer_secret: "" # Optional
    access_token: "" # Optional
    access_token_secret: "" # Optional
  basic_auth:
    enabled: false
    username: "" # Optional
    password: "" # Optional
  jwt:
    enabled: false
    private_key_file: "" # Optional
    signing_method: "" # Optional
    claims: {}
    headers: {}
  tls:
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: "" # Optional
    root_cas_file: "" # Optional
    client_certs: []
```

--
======

Decodes messages automatically from a schema stored within a https://docs.confluent.io/platform/current/schema-registry/index.html[Confluent Schema Registry service^] by extracting a schema ID from the message and obtaining the associated schema from the registry. If a message fails to match against the schema then it will remain unchanged and the error can be caught using xref:configuration:error_handling.adoc[error-handling methods].

Avro, Protobuf and JSON schemas are supported, all are capable of expanding from schema references as of v4.22.0.

== Avro JSON format

By default, this processor expects documents formatted as https://avro.apache.org/docs/current/specification/[Avro JSON^] when decoding with Avro schemas. In this format, the value of a union is encoded in JSON as follows:

- If the union's type is `null`, it is encoded as a JSON `null`.
- Otherwise, the union is encoded as a JSON object with one name/value pair. The name is the type's name, and the value is the recursively-encoded value. The user-specified name is used for Avro's named types (record, fixed, or enum). For other types, the type name is used.

For example, the union schema `["null","string","Transaction"]`, where `Transaction` is a record name, would encode:

- `null` as a JSON `null`
- The string `"a"` as `{"string": "a"}`
- A `Transaction` instance as `{"Transaction": {...}}`, where `{...}` indicates the JSON encoding of a `Transaction` instance

Alternatively, you can create documents in https://pkg.go.dev/github.com/linkedin/goavro/v2#NewCodecForStandardJSONFull[standard/raw JSON format^] by setting the field <<avro-raw_unions,`avro.raw_unions`>> to `true`.

== Protobuf format

This processor decodes Protobuf messages to JSON documents. For more information about the JSON mapping of Protobuf messages, see the https://developers.google.com/protocol-buffers/docs/proto3#json[Protocol Buffers documentation^].

== Metadata

This processor adds the following metadata to processed messages:

- `schema_id`: The ID of the schema in the schema registry associated with the message.

include::redpanda-connect:components:partial$fields/processors/schema_registry_decode.adoc[]

// end::single-source[]