= sql
:type: processor
:commercial-names: SQL
:status: deprecated
:categories: ["Integration"]

// © 2024 Redpanda Data Inc.

component_type_dropdown::[]

[WARNING]
.Deprecated
====
This component is deprecated and will be removed in the next major version release. Please consider moving onto <<alternatives,alternative components>>.
====

Runs an arbitrary SQL query against a database and (optionally) returns the result as an array of objects, one for each row returned.

Introduced in version 3.65.0.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/sql.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/sql.yaml[]
```

--
======

If the query fails to execute then the message will remain unchanged and the error can be caught using xref:configuration:error_handling.adoc[error handling methods].

== Alternatives

For basic inserts or select queries use either the xref:components:processors/sql_insert.adoc[`sql_insert`] or the xref:components:processors/sql_select.adoc[`sql_select`] processor. For more complex queries use the xref:components:processors/sql_raw.adoc[`sql_raw`] processor.

include::redpanda-connect:components:partial$fields/processors/sql.adoc[]

