= sql_raw
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Integration"]

component_type_dropdown::[]

Runs an arbitrary SQL query against a database and (optionally) returns the result as an array of objects, one for each row returned.

ifndef::env-cloud[]
Introduced in version 3.65.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
sql_raw:
  driver: "" # No default (required)
  dsn: "clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60" # No default (required)
  query: INSERT INTO footable (foo, bar, baz) VALUES (?, ?, ?); # No default (required)
  args_mapping: root = [ this.cat.meow, this.doc.woofs[0] ] # No default (optional)
  exec_only: false
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
sql_raw:
  driver: "" # No default (required)
  dsn: "clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60" # No default (required)
  query: INSERT INTO footable (foo, bar, baz) VALUES (?, ?, ?); # No default (required)
  unsafe_dynamic_query: false
  args_mapping: root = [ this.cat.meow, this.doc.woofs[0] ] # No default (optional)
  exec_only: false
  init_files: [] # No default (optional)
  init_statement: | # No default (optional)
    CREATE TABLE IF NOT EXISTS some_table (
      foo varchar(50) not null,
      bar integer,
      baz varchar(50),
      primary key (foo)
    ) WITHOUT ROWID;
  conn_max_idle_time: "" # No default (optional)
  conn_max_life_time: "" # No default (optional)
  conn_max_idle: 2
  conn_max_open: 0 # No default (optional)
```

--
======

If the query fails to execute then the message will remain unchanged and the error can be caught using xref:configuration:error_handling.adoc[error handling methods].

== Examples

[tabs]
======
Table Insert (MySQL)::
+
--

The following example inserts rows into the table footable with the columns foo, bar and baz populated with values extracted from messages.

```yaml
pipeline:
  processors:
    - sql_raw:
        driver: mysql
        dsn: foouser:foopassword@tcp(localhost:3306)/foodb
        query: "INSERT INTO footable (foo, bar, baz) VALUES (?, ?, ?);"
        args_mapping: '[ document.foo, document.bar, meta("kafka_topic") ]'
        exec_only: true
```

--
Table Query (PostgreSQL)::
+
--

Here we query a database for columns of footable that share a `user_id` with the message field `user.id`. A xref:components:processors/branch.adoc[`branch` processor] is used in order to insert the resulting array into the original message at the path `foo_rows`.

```yaml
pipeline:
  processors:
    - branch:
        processors:
          - sql_raw:
              driver: postgres
              dsn: postgres://foouser:foopass@localhost:5432/testdb?sslmode=disable
              query: "SELECT * FROM footable WHERE user_id = $1;"
              args_mapping: '[ this.user.id ]'
        result_map: 'root.foo_rows = this'
```

--
======

== Fields

=== `driver`

A database <<drivers, driver>> to use.

*Type*: `string`

Options:
`clickhouse`
, `gocosmos`
, `mysql`
, `mssql`
, `oracle`
, `postgres`
, `snowflake`
, `spanner`
, `sqlite`
, `trino`

=== `dsn`

A Data Source Name to identify the target database.

==== Drivers

:driver-support: clickhouse=community, gocosmos=community, mssql=community, mysql=certified, oracle=certified, postgres=certified, snowflake=community, spanner=community, sqlite=certified, trino=community

The following is a list of supported drivers, their placeholder style, and their respective DSN formats:

include::components:partial$drivers_table.adoc[]

include::components:partial$drivers_note.adoc[]

*Type*: `string`


```yml
# Examples

dsn: "clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60"

dsn: foouser:foopassword@tcp(localhost:3306)/foodb

dsn: postgres://foouser:foopass@localhost:5432/foodb?sslmode=disable

dsn: oracle://foouser:foopass@localhost:1521/service_name
```

=== `query`

The query to execute. The style of placeholder to use depends on the driver, some drivers require question marks (`?`) whereas others expect incrementing dollar signs (`$1`, `$2`, and so on) or colons (`:1`, `:2` and so on). The style to use is outlined in this table:

include::components:partial$query_table.adoc[]

*Type*: `string`


```yml
# Examples

query: INSERT INTO footable (foo, bar, baz) VALUES (?, ?, ?);

query: SELECT * FROM footable WHERE user_id = $1;
```

=== `unsafe_dynamic_query`

Whether to enable xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions] in the query. Great care should be made to ensure your queries are defended against injection attacks.


*Type*: `bool`

*Default*: `false`

=== `args_mapping`

An optional xref:guides:bloblang/about.adoc[Bloblang mapping] which should evaluate to an array of values matching in size to the number of placeholder arguments in the field `query`.


*Type*: `string`


```yml
# Examples

args_mapping: root = [ this.cat.meow, this.doc.woofs[0] ]

args_mapping: root = [ meta("user.id") ]
```

=== `exec_only`

Whether the query result should be discarded. When set to `true` the message contents will remain unchanged, which is useful in cases where you are executing inserts, updates, etc.


*Type*: `bool`

*Default*: `false`

=== `init_files`

An optional list of file paths containing SQL statements to execute immediately upon the first connection to the target database. This is a useful way to initialise tables before processing data. Glob patterns are supported, including super globs (double star).

Care should be taken to ensure that the statements are idempotent, and therefore would not cause issues when run multiple times after service restarts. If both `init_statement` and `init_files` are specified the `init_statement` is executed _after_ the `init_files`.

If a statement fails for any reason a warning log will be emitted but the operation of this component will not be stopped.


*Type*: `array`

ifndef::env-cloud[]
Requires version 4.10.0 or newer
endif::[]

```yml
# Examples

init_files:
  - ./init/*.sql

init_files:
  - ./foo.sql
  - ./bar.sql
```

=== `init_statement`

An optional SQL statement to execute immediately upon the first connection to the target database. This is a useful way to initialise tables before processing data. Care should be taken to ensure that the statement is idempotent, and therefore would not cause issues when run multiple times after service restarts.

If both `init_statement` and `init_files` are specified the `init_statement` is executed _after_ the `init_files`.

If the statement fails for any reason a warning log will be emitted but the operation of this component will not be stopped.


*Type*: `string`

ifndef::env-cloud[]
Requires version 4.10.0 or newer
endif::[]

```yml
# Examples

init_statement: |2
  CREATE TABLE IF NOT EXISTS some_table (
    foo varchar(50) not null,
    bar integer,
    baz varchar(50),
    primary key (foo)
  ) WITHOUT ROWID;
```

=== `conn_max_idle_time`

An optional maximum amount of time a connection may be idle. Expired connections may be closed lazily before reuse. If `value <= 0`, connections are not closed due to a connections idle time.


*Type*: `string`


=== `conn_max_life_time`

An optional maximum amount of time a connection may be reused. Expired connections may be closed lazily before reuse. If `value <= 0`, connections are not closed due to a connections age.


*Type*: `string`


=== `conn_max_idle`

An optional maximum number of connections in the idle connection pool. If conn_max_open is greater than 0 but less than the new conn_max_idle, then the new conn_max_idle will be reduced to match the conn_max_open limit. If `value <= 0`, no idle connections are retained. The default max idle connections is currently 2. This may change in a future release.


*Type*: `int`

*Default*: `2`

=== `conn_max_open`

An optional maximum number of open connections to the database. If conn_max_idle is greater than 0 and the new conn_max_open is less than conn_max_idle, then conn_max_idle will be reduced to match the new conn_max_open limit. If `value <= 0`, then there is no limit on the number of open connections. The default is 0 (unlimited).


*Type*: `int`

// end::single-source[]