= switch
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Composition"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Conditionally processes messages based on their contents.

```yml
# Config fields, showing default values
label: ""
switch: [] # No default (required)
```

For each switch case a xref:guides:bloblang/about.adoc[Bloblang query] is checked and, if the result is true (or the check is empty) the child processors are executed on the message.

include::redpanda-connect:components:partial$fields/processors/switch.adoc[]

include::redpanda-connect:components:partial$examples/processors/switch.adoc[]

== Batching

When a switch processor executes on a xref:configuration:batching.adoc[batch of messages] they are checked individually and can be matched independently against cases. During processing the messages matched against a case are processed as a batch, although the ordering of messages during case processing cannot be guaranteed to match the order as received.

At the end of switch processing the resulting batch will follow the same ordering as the batch was received. If any child processors have split or otherwise grouped messages this grouping will be lost as the result of a switch is always a single batch. In order to perform conditional grouping and/or splitting use the xref:components:processors/group_by.adoc[`group_by` processor].

// end::single-source[]