= while
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Composition"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


A processor that checks a xref:guides:bloblang/about.adoc[Bloblang query] against each batch of messages and executes child processors on them for as long as the query resolves to true.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/processors/while.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/processors/while.yaml[]
```

--
======

The field `at_least_once`, if true, ensures that the child processors are always executed at least one time (like a do .. while loop.)

The field `max_loops`, if greater than zero, caps the number of loops for a message batch to this value.

If following a loop execution the number of messages in a batch is reduced to zero the loop is exited regardless of the condition result. If following a loop execution there are more than 1 message batches the query is checked against the first batch only.

The conditions of this processor are applied across entire message batches. You can find out more about batching xref:configuration:batching.adoc[in this doc].

include::redpanda-connect:components:partial$fields/processors/while.adoc[]

// end::single-source[]