= Redpanda Data Documentation Style Guidelines

== Notes and warnings

Redpanda documentation uses AsciiDoc admonitions:

[cols="1,1",options="header"]
|===
| Notice | Description

| NOTE
| A supplement to the documentation with helpful information.

| TIP
| Describes a way to make things easier or indicates a best practice.

| CAUTION
| A warning that certain behavior is unexpected or may have unintended consequences.

| IMPORTANT
| An important note.
|===

== Numbers

For whole numbers between one and nine, spell out the number (for example, nine instead of 9). For numbers greater than 9, or any decimal or negative number, use Arabic numerals (for example, 1.5 or -2).

* *Correct:* To run Redpanda in a three-node cluster, use this command: `rpk container start -n 3`
* *Incorrect:* To run Redpanda in a 3-node cluster, use this command: `rpk container start -n 3`

The exception to this is within code blocks or when you're referring to a default value. For example:

* *Correct:* cloud_storage_upload_ctrl_d_coeff - The derivative coefficient for the upload controller. Default is 0.
* *Incorrect:* cloud_storage_upload_ctrl_d_coeff - The derivative coefficient for the upload controller. Default is zero.

