content_dir: "/modules"
reviewer:
  custom_style_guide:
    enabled: true
    path_to_style_guide_dir: .hyperlint/reviewer/custom-style-guide
  vale_style_guide:
    check_status_upon_review_failure: failure
    enabled: true
    path_to_vale_ini_file: .hyperlint/reviewer/vale-style-guide/.vale.ini
