# tag::config[]
input:
  generate:
    mapping: |
      root.jql = "assignee = currentUser() AND status IN (Open, 'In Progress') ORDER BY updated DESC"
      root.maxResults = 20
      root.fields = [
        "key",
        "summary",
        "status",
        "assignee",
        "priority",
        "created",
        "updated",
        "customfield_10001"  # Custom field ID
      ]
      root.startAt = 0
    interval: 60s

pipeline:
  processors:
    - jira:
        base_url: "${JIRA_BASE_URL}"
        username: "${JIRA_USERNAME}"
        api_token: "${JIRA_API_TOKEN}"
        max_results_per_page: 100

    # Transform each individual issue message
    - mapping: |
        root.key = this.key
        root.summary = this.fields.summary
        root.status = this.fields.status.name
        root.priority = this.fields.priority.name
        root.custom_field = this.fields.customfield_10001

output:
  kafka:
    addresses: ["localhost:9092"]
    topic: jira-issues
# end::config[]
