= aws_dynamodb
// tag::single-source[]
:type: cache
:status: stable

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Stores key/value pairs as a single document in a DynamoDB table. The key is stored as a string value and used as the table hash key. The value is stored as
a binary value using the `data_key` field name.

ifndef::env-cloud[]
Introduced in version 3.36.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
aws_dynamodb:
  table: "" # No default (required)
  hash_key: "" # No default (required)
  data_key: "" # No default (required)
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
aws_dynamodb:
  table: "" # No default (required)
  hash_key: "" # No default (required)
  data_key: "" # No default (required)
  consistent_read: false
  default_ttl: "" # No default (optional)
  ttl_key: "" # No default (optional)
  retries:
    initial_interval: 1s
    max_interval: 5s
    max_elapsed_time: 30s
  region: "" # No default (optional)
  endpoint: "" # No default (optional)
  credentials:
    profile: "" # No default (optional)
    id: "" # No default (optional)
    secret: "" # No default (optional)
    token: "" # No default (optional)
    from_ec2_role: false
    role: "" # No default (optional)
    role_external_id: "" # No default (optional)
```

--
======

A prefix can be specified to allow multiple cache types to share a single DynamoDB table. An optional TTL duration (`ttl`) and field
(`ttl_key`) can be specified if the backing table has TTL enabled.

Strong read consistency can be enabled using the `consistent_read` configuration field.

== Fields

[data_template, redpanda-connect:ROOT:example$connect.json, redpanda-connect:ROOT:example$overrides.json]
--

{{#selectByJsonPath this "$.caches[?(@.name=='aws_dynamodb')]"}}

{{renderConnectFields this.config.children}}

{{renderConnectExamples this.config.children}}

{{/selectByJsonPath}}


// end::single-source[]