= memory
// tag::single-source[]
:type: cache
:status: stable

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Stores key/value pairs in a map held in memory. This cache is therefore reset every time the service restarts. Each item in the cache has a TTL set from the moment it was last edited, after which it will be removed during the next compaction.


[tabs]
======
Common::
+
--

```yml
include::components:example$common/caches/memory.yaml[]
```

--
Advanced::
+
--

```yml
include::components:example$advanced/caches/memory.yaml[]
```

--
======

The compaction interval determines how often the cache is cleared of expired items, and this process is only triggered on writes to the cache. Access to the cache is blocked during this process.

Item expiry can be disabled entirely by setting the `compaction_interval` to an empty string.

The field `init_values` can be used to prepopulate the memory cache with any number of key/value pairs which are exempt from TTLs:

```yaml
cache_resources:
  - label: foocache
    memory:
      default_ttl: 60s
      init_values:
        foo: bar
```

These values can be overridden during execution, at which point the configured TTL is respected as usual.

include::redpanda-connect:components:partial$fields/caches/memory.adoc[]

// end::single-source[]