= redpanda
// tag::single-source[]
:type: cache
:status: beta
:categories: [Services]
:description: A Kafka cache using the https://github.com/twmb/franz-go[Franz Kafka client library^].

component_type_dropdown::[]

A Kafka cache implemented using the https://github.com/twmb/franz-go[Franz Kafka client library^].

[tabs]
======
Common::
+
--
```yaml
include::components:example$common/caches/redpanda.yaml[]
```
--
Advanced::
+
--
```yaml
include::components:example$advanced/caches/redpanda.yaml[]
```
--
======

A cache that stores data in a Kafka topic.

This cache is useful for data that is written frequently and queried infrequently.
Reads from the cache require scanning the entire topic partition. If you expect frequent access, consider placing an in-memory caching layer in front of this one.

Because only the latest values are needed, configure compaction for topics used as caches so that reads are less expensive when topics are rescanned. See xref:ROOT:manage:cluster-maintenance/compaction-settings.adoc[].

The cache does not have any TTL mechanisms. Use the Kafka topic retention policies to manage TTL.


include::redpanda-connect:components:partial$fields/caches/redpanda.adoc[]


// end::single-source[]