= redpanda
// tag::single-source[]
:type: cache
:status: beta
:categories: [Services]
:description: A Kafka cache using the https://github.com/twmb/franz-go[Franz Kafka client library^].

component_type_dropdown::[]

A Kafka cache implemented using the https://github.com/twmb/franz-go[Franz Kafka client library^].

[tabs]
======
Common::
+
--
```yaml
cache:
  label: ""
  redpanda:
    seed_brokers: [] # No default (required)
    topic: "" # No default (required)
```
--
Advanced::
+
--
```yaml
cache:
  label: ""
  redpanda:
    seed_brokers: [] # No default (required)
    client_id: benthos

    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs:
        cert: ""
        key: ""
        cert_file: ""
        key_file: ""
        password: ""

    sasl:
      mechanism: "" # No default (required)
      username: ""
      password: ""
      token: ""
      extensions: "" # No default (optional)
      aws:
        region: "" # No default (optional)
        endpoint: "" # No default (optional)
        credentials:
          profile: "" # No default (optional)
          id: "" # No default (optional)
          secret: "" # No default (optional)
          token: "" # No default (optional)
          from_ec2_role: "" # No default (optional)
          role: "" # No default (optional)
          role_external_id: "" # No default (optional)

    metadata_max_age: 5m
    request_timeout_overhead: 10s
    conn_idle_timeout: 20s
    topic: "" # No default (required)
```
--
======

A cache that stores data in a Kafka topic.

This cache is useful for data that is written frequently and queried infrequently.
Reads of the cache require reading the entire topic partition, so if there is a need for frequent reads, it's recommended to put an in memory caching layer infront of this cache.

Topics that are used as caches should be compacted so that reads are less expensive when they rescan the topic, as only the latest value is needed.

This cache does not support any special TTL mechanism, any TTL should be handled by the Kafka topic itself using data retention policies.


include::redpanda-connect:components:partial$fields/caches/redpanda.adoc[]


// end::single-source[]