= sql
// tag::single-source[]
:type: cache
:status: experimental
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Uses an SQL database table as a destination for storing cache key/value items.

ifndef::env-cloud[]
Introduced in version 4.26.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
sql:
  driver: "" # No default (required)
  dsn: "clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60" # No default (required)
  table: foo # No default (required)
  key_column: foo # No default (required)
  value_column: bar # No default (required)
  set_suffix: ON DUPLICATE KEY UPDATE bar=VALUES(bar) # No default (optional)
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
sql:
  driver: "" # No default (required)
  dsn: "clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60" # No default (required)
  table: foo # No default (required)
  key_column: foo # No default (required)
  value_column: bar # No default (required)
  set_suffix: ON DUPLICATE KEY UPDATE bar=VALUES(bar) # No default (optional)
  init_files: [] # No default (optional)
  init_statement: | # No default (optional)
    CREATE TABLE IF NOT EXISTS some_table (
      foo varchar(50) not null,
      bar integer,
      baz varchar(50),
      primary key (foo)
    ) WITHOUT ROWID;
  conn_max_idle_time: "" # No default (optional)
  conn_max_life_time: "" # No default (optional)
  conn_max_idle: 2
  conn_max_open: 0 # No default (optional)
```

--
======

Each cache key/value pair will exist as a row within the specified table. Currently only the key and value columns are set, and therefore any other columns present within the target table must allow NULL values if this cache is going to be used for set and add operations.

Cache operations are translated into SQL statements as follows:

== Get

All `get` operations are performed with a traditional `select` statement.

== Delete

All `delete` operations are performed with a traditional `delete` statement.

== Set

The `set` operation is performed with a traditional `insert` statement.

This will behave as an `add` operation by default, and so ideally needs to be adapted in order to provide updates instead of failing on collision	s. Since different SQL engines implement upserts differently it is necessary to specify a `set_suffix` that modifies an `insert` statement in order to perform updates on conflict.

== Add

The `add` operation is performed with a traditional `insert` statement.

include::redpanda-connect:components:partial$fields/caches/sql.adoc[]

// end::single-source[]