= Install or Upgrade with rpk
:description: Install or upgrade Redpanda Connect using the Redpanda CLI.
:page-aliases: get-started:upgrade/rpk-upgrade.adoc

The Redpanda CLI (`rpk`) is the recommended way to install, upgrade, and manage Redpanda Connect on bare metal. It provides a simple, automated workflow for most users.

== Install

To install Redpanda Connect using the Redpanda CLI, choose your platform:

=== Linux

include::ROOT:get-started:partial$install-rpk-linux.adoc[]

==== FIPS compliance

include::components:partial$enterprise_feature_note.adoc[]

To install `rpk` to run the latest version of Redpanda Connect in FIPS-compliant mode, you must install the `redpanda-rpk-fips` and `redpanda-connect-fips` packages. Both packages are built using the https://github.com/microsoft/go[Microsoft GoLang compiler^] and the https://github.com/microsoft/go-crypto-openssl[Microsoft’s Go Crypto OpenSSL package^], which uses the FIPS-approved version of OpenSSL.

IMPORTANT: The packages for FIPS-compliant `rpk` (`redpanda-rpk-fips`) and Redpanda `rpk` (`redpanda-rpk`) are mutually exclusive, and so cannot be installed in the same environment.

[tabs]
=====
RHEL::
+
--
. To make sure your distribution is up to date, run:
+
[,bash]
----
sudo dnf upgrade
----
. Add `redpanda` to your `dnf` list of repositories. 
+
[,bash]
----
curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.rpm.sh' | \
sudo -E bash
----
. Install Redpanda packages for FIPS compliance.
+
[,bash]
----
sudo dnf install -y redpanda-rpk-fips redpanda-connect-fips
----

. Verify your installation.
+
[,bash]
----
rpk connect --version
----
To keep up-to-date with Redpanda Connect releases, run the following command:
[,bash]
----
sudo dnf update
----
--
Debian/Ubuntu::
+
--
. To make sure your distribution is up to date, run:
+
[,bash]
----
sudo apt upgrade 
----
. Add `redpanda` to your `apt` list of repositories. 
+
[,bash]
----
curl -1sLf 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh' | sudo -E bash 
----
. Install Redpanda packages for FIPS compliance.
+
[,bash]
----
sudo apt install -y redpanda-rpk-fips redpanda-connect-fips 
----
. Verify your installation.
+
[,bash]
----
rpk connect --version
----
To keep up-to-date with the Redpanda Connect releases, run the following command:
[,bash]
----
sudo apt update
----
--
=====

=== MacOS

include::ROOT:get-started:partial$install-rpk-macos.adoc[]

=== Docker

To use `rpk` in Docker, you can use the Redpanda Docker image, which includes both Redpanda and `rpk` as part of the installation.
[source,bash]
----
docker pull docker.redpanda.com/redpandadata/connect
----

== Upgrade

Redpanda Connect uses the `rpk connect` plugin to manage upgrades, which is automatically installed when you start to run `rpk connect` commands from the `rpk` CLI. You do not need to upgrade the entire Redpanda CLI.

Check the version of Redpanda Connect already installed

[,bash]
----
rpk connect --version
----

=== Upgrade to the latest version

The simplest way to upgrade is to use the `rpk connect upgrade` command:

[,bash]
----
rpk connect upgrade
----

Example output:

[,bash,subs="attributes+"]
----
Redpanda Connect successfully upgraded from 4.38.0 to the latest version ({latest-connect-version}).
----

For a full list of `rpk connect upgrade` options, run:

[,bash]
----
rpk connect upgrade --help
----

=== Upgrade to a specific version

Force an upgrade (or downgrade) to a specific version of Redpanda Connect using the following command:

[,bash]
----
rpk connect install --connect-version <version> --force
----

Replace the `<version>` placeholder with the full version number, for example: `4.38.0`. You may need to wait a few seconds before the installation completes.

Example output:

[,bash]
----
Redpanda Connect 4.38.0 successfully installed.
----

== Uninstall

If you no longer want to use Redpanda Connect, you can uninstall the `rpk connect` plugin from the CLI:

[,bash]
----
rpk connect uninstall
----

Example output:

[,bash]
----
PATH                                                MESSAGE
/Users/username/.local/bin/.rpk.managed-connect     OK
----

NOTE: After upgrading (or downgrading), you must restart a pipeline to use features in the Redpanda Connect version you have deployed.

== Next steps

Explore the available connectors in the xref:components:about.adoc[catalog].