= Monitoring
:description: Learn how to monitor Redpanda Connect, including setting up metrics and alerts to ensure system health and performance.

== Health checks

Redpanda Connect serves two HTTP endpoints for health checks:

* `/ping` can be used as a liveness probe as it always returns a 200.
* `/ready` can be used as a readiness probe as it serves a 200 only when both the input and output are connected, otherwise a 503 is returned.

== Metrics

Redpanda Connect xref:components:metrics/about.adoc#metric_names[exposes lots of metrics] either to Statsd, Prometheus, Cloudwatch or for debugging purposes an HTTP endpoint that returns a JSON formatted object.

The target destination of Redpanda Connect metrics is configurable from the xref:components:metrics/about.adoc[metrics section], where it's also possible to rename and restrict the metrics that are emitted with mappings.

== Tracing

Redpanda Connect also xref:components:tracers/about.adoc[emits opentracing events] to a tracer of your choice, which can be used to visualise the processors within a pipeline.
