= Upgrade Redpanda Connect using the Helm Chart
:description: Upgrade Redpanda Connect on Kubernetes using Helm.

To benefit from Redpanda Connect's new features and enhancements, upgrade to use the latest version of the Redpanda Helm chart.

== Upgrade Redpanda Connect

To upgrade Redpanda Connect to a newer chart version:

. Ensure your Helm repository is updated to fetch the latest version of the Redpanda chart:
+
[,bash]
----
helm repo update
----

. Upgrade your existing deployment using the https://helm.sh/docs/helm/helm_upgrade/[`helm upgrade`] command:
+
[,bash]
----
helm upgrade redpanda-connect redpanda/connect --namespace <namespace> --values <your-values-file>
----
+
Replace `<your-values-file>` with the path to your custom configuration file.

== Roll back an upgrade

If an upgrade introduces issues, you can roll back to a previous release. Helm retains previous deployments, allowing you to roll back with the https://helm.sh/docs/helm/helm_rollback/[`helm rollback`] command:

[,bash]
----
helm rollback redpanda-connect <revision-number> --namespace <namespace>
----

To find the revision number, use the https://helm.sh/docs/helm/helm_history/[`helm history`] command:

[,bash]
----
helm history redpanda-connect --namespace <namespace>
----

This command lists previous deployments and their revision numbers.

See also:

* xref:get-started:quickstarts/helm-chart.adoc[]